### ISSUE TITLE
Issue running version 0.12.0 via linux binary

### ISSUE THREAD

**Issue by neilmusgrove** [etesync/etesync-dav#100]
Hi, I attempted to update to 0.12.0 overwriting my binary from the previous version. Running it in a terminal gives the following message:

`[9532] Error loading Python lib '/tmp/_MEINAmCEr/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.28' not found (required by /tmp/_MEINAmCEr/libpython3.7m.so.1.0)`

**Comment by tasn** [comment]
The python:3.7 docker tag we depended on upgraded to debian Buster which has a new glibc which was made the new baseline requirement.
I changed the dockerfile to depend on debian stretch (old glibc) and uploaded a new binary based on that.

Please let me know if you are still encountering any issues.

**Comment by neilmusgrove** [comment]
Resolves the issue, thanks

**Comment by tasn** [comment]
Great to hear, thanks for the update. :)
