### ISSUE TITLE
With KDE Akonadi 5.12.3: In transformToNative, unhandled exception on line None: <class 'ValueError'>: unknown parameter name

### ISSUE THREAD

**Issue by devurandom** [etesync/etesync-dav#102]
I noticed that my address book does not sync in Akonadi / KAddressBook, so I investigated and found this:
```
❯ systemctl --user status etesync-dav
[...]
etesync-dav[79745]:    Use a production WSGI server instead.
etesync-dav[79745]:  * Debug mode: off
etesync-dav[79745]:  * Running on http://127.0.0.1:37359/ (Press CTRL+C to quit)
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:53] "GET /user/email%40example.com HTTP/1.1" 302 -
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:53] "GET /login/ HTTP/1.1" 200 -
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:53] "GET /favicon.ico HTTP/1.1" 404 -
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:54] "POST /login/ HTTP/1.1" 302 -
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:54] "GET / HTTP/1.1" 200 -
etesync-dav[79745]: 127.0.0.1 - - [06/Dec/2019 15:19:58] "GET /user/email%40example.com HTTP/1.1" 200 -
etesync-dav[79745]: [7fbed5982700] WARNING: Bad PUT request on '/email@example.com/LONG-HASH/1575644163.R271.ics': "In transformToNative, unhandled exception on line None: <class 'ValueError'>: unknown parameter name (<VTIMEZONE| [<TZID{}Europe/Berlin>, <STANDARD| [<DTSTART{}19971026T030000>, <RRULE{}FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10>, <TZNAME{}CET>, <TZOFFSETFROM{}+0200>, <TZOFFSETTO{}+0100>]>, <STANDARD| [<DTSTART{}19800928T030000>, <RDATE{}19950924T030000>, <RRULE{}ERROR: No Value>, <TZNAME{}CET>, <TZOFFSETFROM{}+0200>, <TZOFFSETTO{}+0100>]>, <DAYLIGHT| [<DTSTART{}19800406T010000>, <RDATE{}19800406T010000>, <TZNAME{}CEST>, <TZOFFSETFROM{}+0000>, <TZOFFSETTO{}+0200>]>, <DAYLIGHT| [<DTSTART{}19810329T020000>, <RRULE{}FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3>, <TZNAME{}CEST>, <TZOFFSETFROM{}+0100>, <TZOFFSETTO{}+0200>]>]>)"

❯ etesync-dav --version
EteSync DAV version:  0.13.0
Radicale version:  2.1.11

❯ akonadictl --version
akonadictl 5.12.3
```

According to akonadiconsole, my EteSync Akonadi DAV groupware resource is now stuck in "Fetching collections (0%)".

**Comment by tasn** [comment]
VTIMEZONE (what the error is about) is about events, and `.ics` is the file suffix for events. Are you sure you are trying to sync contacts? Because whatever is connecting to your etesync address book is trying to push an event, not a contact.

**Comment by devurandom** [comment]
I have set up Akonadi to sync both the calendar and the address book. I assume it tries the calendar first and gets itself stuck when that fails.

**Comment by tasn** [comment]
Sorry for the delay in reply. If you only set up calendar, do things work correctly? Could you try removing both accounts from akonadi, and start from scratch? Because I still stand behind my previous comment. The problem is that Akonadi is trying to connect to the wrong one.

Could you maybe also describe step by step how you added the account? Because there's an issue with the Evolution client that sounds like it may be related to here. Essentially, it's possible that the address book is showing as a valid calendar and you accidentally used that one. The only way to know is to start from scratch.

**Comment by devurandom** [comment]
After deleting the Akonadi resource and re-creating it, I can no longer reproduce this.

**Comment by tasn** [comment]
Great to hear, and thanks for the update! I bet it was what I guessed above, that Akonadi added the wrong calendar account which was causing issues.
