### ISSUE TITLE
Cannot sync with ubuntu 18.04

### ISSUE THREAD

**Issue by tsterbak** [etesync/etesync-dav#106]
I followed the steps in the README for the setup with GNOME and it seems to work fine, but I'm not getting the calendar events added with the android client. The Web-UI shows the events added in the android client but not the events added in Evolution.

Is this an expected behavior or am I missing something?

Thanks a lot for this great project!

**Comment by tasn** [comment]
Just to get this clear: sync works in all directions, except for being sent from Evolution (etesync-dav) to the rest of the clients?
Do you see anything suspicious (errors) in etesync-dav's output?

**Comment by tsterbak** [comment]
Thanks a lot for your fast reply!

Sorry for not being more clear. No, sync works between android and your server.With Evolution (etesync-dav) it works in no direction. I can login my account there and create events that etesync picks up, but nothing is synced. Also, my contacts have been pulled from the server even though I haven't created and adressbook, but I can see them in `/.config/etesync/etesync_data.db/`.

From the logs I get the feeling, that this issue in radicale could be the problem here:
https://github.com/Kozea/Radicale/issues/839
I'm using a encryption password, that contains non-ASCII characters. But I can create a local user with my account password and this encryption password. In the logs everything looks fine. But when I click on the calendar link in the local EteSync DAV Management (0.14.0), I'm getting  `A server error occurred.  Please contact the administrator.` and in the logs
```
[7fbe69440700] DEBUG: Sanitized script name: ''                                                              
[7fbe69440700] DEBUG: Sanitized path: '/example@mail.com/48c8adcdd16b60/'                                                    
[7fbe69440700] ERROR: An exception occurred during GET request on '/example@mail.com/48c8adcdd16b60/': comparing strings with non-ASCII characters
is not supported                                                                                                                                                                                            Traceback (most recent call last):                                                                                                                                                                            File "site-packages/radicale/__init__.py", line 332, in __call__                                                                                                                                    
  File "site-packages/radicale/__init__.py", line 461, in _handle_request
  File "site-packages/radicale/auth.py", line 115, in is_authenticated2
  File "site-packages/radicale/auth.py", line 255, in is_authenticated
  File "site-packages/radicale/auth.py", line 191, in _plain
TypeError: comparing strings with non-ASCII characters is not supported
```

**Comment by tasn** [comment]
Thanks for the clarification, this is weird, because the radicale password indeed should not have non-ascii characters, because we generate it ourselves.
More specifically: when setting up Evolution, did you copy the **new** dav password you got from etesync-dav? I'm specifically talking about step 3 in https://github.com/etesync/etesync-dav#configuration-and-running

Because this is the password you should be using with Evolution, not your encryption password, and neither your etesync password. Having the data in `.config/etesync/etesync_data.db` is an indication things are working well other than just the radicale part.

**Comment by tsterbak** [comment]
I figured it out now. It was indeed something weird...
For some reason I had one strange contact entry (it had a relationship status with non-ASCII chracters). The parsing for this entry failed. After deleting the etesync adressbook, cleaning the entry in my contacts and importing the contacts to a new adressbook everything works fine! Thanks a lot for your support!

**Comment by tasn** [comment]
Interesting. Thanks for the update and good job figuring it out! :)
