### ISSUE TITLE
Can't Login from http://localhost:37359

### ISSUE THREAD

**Issue by ChasNelson1990** [etesync/etesync-dav#110]
Hi there,
I don't seem to be able to login to the web interface anymore?

Using the AUR version of etesync on Arch Linux: EteSync DAV version:  0.14.2 and Radicale version:  2.1.11.

I ran `etesync-dav manage get <USER>` to check my username and password are correct but if I use these in the web login, I get a 'Username or password incorrect.' error.

Had a look at recent issues but didn't see anything like this.

Using `--debug` gives me nothing but GETs and POSTs.

Any ideas?
Chas

**Comment by tasn** [comment]
The web management UI now accepts your *EteSync* password, not the dav password. So not the ones returned from `manage get`, but rather the one you use to login to etesync.com.

I'm closing this, as I believe it's solved. Let me know if it isn't, and I'll repoen.

**Comment by ChasNelson1990** [comment]
Gah! Sorry. Yes, all fine now.

**Comment by tasn** [comment]
Not your fault, it used to be the dav password, but it was changed with the move to the new web ui.
