### ISSUE TITLE
Two cores at 100% CPU usage during sync

### ISSUE THREAD

**Issue by Peter4487** [etesync/etesync-dav#119]
I'm seeing this error during periods of two processes at ~100% usage of a CPU core:
[alphanumerics] WARNING: Client provided invalid sync token 'http://radicale.org/ns/sync/[alphanumeric string]': Sync token are not supported (you can ignore this warning)

I see it seven times during one sync / instance of 2x100% CPU usage.

_Originally posted by @Peter4487 in https://github.com/etesync/etesync-dav/issues/93#issuecomment-589727559_

**Comment by tasn** [comment]
Sorry it took a bit of time. I think version 0.15.1 that I'm releasing now may fix things for you. Please let me know.

**Comment by Peter4487** [comment]
Hi, sorry for the delay
I was still seeing 2 x 100% CPU usage with 0.15.1; I've just updated to 0.16.0 and will watch.

**Comment by tasn** [comment]
:cry: 

I actually made some more relevant improvements in 0.16.0, so even if not fixed, it should at least significantly improved. So please let me know.

**Comment by tasn** [comment]
OK, it definitely won't be the case anymore if you update to EteSync 2.0. We just overhauled this thing and reduce a lot of the CPU usage in general. I'm closing this. Please reopen if it's not the case.
