### ISSUE TITLE
Error: Cannot contain both DTEND and DURATION components

### ISSUE THREAD

**Issue by CodingCellist** [etesync/etesync-dav#120]
When trying to sync the Thunderbird calendar on my laptop, I got the following error message from the flask app:
```
ERROR: An exception occurred during PUT request on '[...].ics': 'VEVENT components cannot contain both DTEND and DURATION                     components'
```

I am uncertain as to why this is happening and for which event. I'd be happy to provide more details if there is a place to narrow them down.

**Comment by tasn** [comment]
Is it when uploading from Thunderbird or downloading to it? Looks like uploading from.

Anyhow, the easiest way to find the correct event is to search for `[...]` (as in, the uid you redacted) in the .ics file you loaded into Thunderbird, and then you'll be able to see which event it is, and if it really has but duration and dtend (which is indeed invalid).

**Comment by CodingCellist** [comment]
Sorry, I forgot to specify: It was when trying to upload from TB.

Interestingly, the issue seems to have gone away in the mean time. I don't know if it was simply a case of TB taking some time to delete an event from its internal system or what it was, but in any case the issue appears to be solved now, so I'll close the issue

Thank you for the trouble-shooting guide though. It will definitely be useful should the issue pop up again.

**Comment by tasn** [comment]
Great, please keep an eye out and let me know. :)
