### ISSUE TITLE
Catalina woes

### ISSUE THREAD

**Issue by embamba** [etesync/etesync-dav#128]
I just finally updated my Mac to Catalina. But the web interface at localhost:37358 is no longer accessible. I get a message in Safari, for example, that reads "Safari can't open the page 'localhost:37358' because the server unexpectedly dropped the connection. Wait for a few minutes, then try again."

I'd gotten this a month or so ago, one day, and updating etesync-dav to the latest version solved it. But I'm already on that and things are not working as they should.

I deleted the localhost certificate and the contents of ~/Library/Application Support/etesync-dav/ and ran the instance again. That got me the expected web interface login and a prompt to set up SSL. Which I did. But when I restarted etesync-dav, I again lost access to localhost:37358.

Any ideas?

**Comment by tasn** [comment]
I just released v0.17.0 that may fix this issue. The issue was actually fixed a while back, but apparently I forgot to make a release with it.

Please reopen this ticket if it still fails.

**Comment by embamba** [comment]
No change. Still the same behavior.

    On Monday, May 11, 2020, 6:33:05 AM PDT, Tom Hacohen <notifications@github.com> wrote:  
 
 


I just released v0.17.0 that may fix this issue. The issue was actually fixed a while back, but apparently I forgot to make a release with it.

Please reopen this ticket if it still fails.

**Comment by tasn** [comment]
Have you updated to 0.17.0? And made sure the latest version is running?
Could you please come to https://www.etesync.com/community-chat/ so we can try a few things in a more synchronous manner?

**Comment by embamba** [comment]
Yes, I'm on 0.17.0. I'll come to the chat when I can.

    On Tuesday, May 12, 2020, 12:04:49 AM PDT, Tom Hacohen <notifications@github.com> wrote:  
 
 


Have you updated to 0.17.0? And made sure the latest version is running?
Could you please come to https://www.etesync.com/community-chat/ so we can try a few things in a more synchronous manner?

**Comment by tasn** [comment]
Great, looking forward. We are mostly there, but may take a bit of time to answer sometimes, so don't immediately run away.

**Comment by tasn** [comment]
We figured it out in the chat, the issue was local (problem with the certificate not being trusted) rather than something with etesync-dav.
