### ISSUE TITLE
PermissionError: [Errno 13] Permission denied:

### ISSUE THREAD

**Issue by dwuttke90** [etesync/etesync-dav#13]
Hey there,

seems like this is the service i was actually looking for. android app works fine as it seems.
cant get the desktop one to work. im on arch linux and this is the stacktrace i get.

the file whic gets the "permission denied" doesnt exist...

Any idea whats wrong here?

`pip install etesync-dav       
Collecting etesync-dav
  Using cached etesync-dav-0.1.5.tar.gz
Requirement already satisfied: appdirs>=1.4.3 in /usr/lib/python3.6/site-packages (from etesync-dav)
Collecting radicale_storage_etesync>=0.1.4 (from etesync-dav)
  Using cached radicale_storage_etesync-0.1.4.tar.gz
Collecting etesync>=0.5.1 (from radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached etesync-0.5.2.tar.gz
Collecting Radicale>=2.0.0 (from radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached Radicale-2.1.8.tar.gz
Collecting asn1crypto>=0.22 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl
Collecting cffi>=1.10 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting coverage>=4.3 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached coverage-4.5.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cryptography>=1.9 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached cryptography-2.1.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting furl>=0.5 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached furl-1.0.1.tar.gz
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.6/site-packages (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Collecting orderedmultidict>=0.7 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached orderedmultidict-0.7.11.tar.gz
Requirement already satisfied: packaging>=16.8 in /usr/lib/python3.6/site-packages (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Collecting peewee>=2.9 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached peewee-3.1.5.tar.gz
Collecting py>=1.4 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached py-1.5.2-py2.py3-none-any.whl
Collecting pyasn1>=0.2 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached pyasn1-0.4.2-py2.py3-none-any.whl
Collecting pycparser>=2.17 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached pycparser-2.18.tar.gz
Requirement already satisfied: pyparsing>=2.2 in /usr/lib/python3.6/site-packages (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Collecting scrypt>=0.8.0 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached scrypt-0.8.6.tar.gz
Collecting python-dateutil>=2.6 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached python_dateutil-2.7.0-py2.py3-none-any.whl
Requirement already satisfied: requests>=2.13 in /usr/lib/python3.6/site-packages (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Requirement already satisfied: six>=1.10 in /usr/lib/python3.6/site-packages (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Collecting vobject>=0.9 (from etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
  Using cached vobject-0.9.5.tar.gz
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.6/site-packages (from requests>=2.13->etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.13->etesync>=0.5.1->radicale_storage_etesync>=0.1.4->etesync-dav)
Installing collected packages: asn1crypto, pycparser, cffi, coverage, cryptography, orderedmultidict, furl, peewee, py, pyasn1, scrypt, python-dateutil, vobject, etesync, Radicale, radicale-storage-etesync, etesync-dav
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/asn1crypto-0.24.0.dist-info'
pip install etesync-dav  9,52s user 0,40s system 95% cpu 10,389 total`

**Comment by tasn** [comment]
I guess I need to improve the installation instructions, will do so now.

`pip install` is meant to be run as either root, or better yet in a virtual/package environment.

To run in a virtualenv, make sure you have `python-virtualenv` installed, and then run:

`virtualenv /home/USER/path/to/where/you/want/it/installed` 

followed by

`source /the/same/path/bin/activate`

and then `pip install as shown in the instructions`.

Now every time you want to run it, you'd need to first run the `source` command from above (better to wrap it in a script probably).

This is how you'd run it in this case, though it's better if the whole process is just handled by your distro's package maintainers. I'll try to maybe create an AUR package this weekend. It shouldn't be too hard since the python etesync bindings are already in the arch community repos.

**Comment by dwuttke90** [comment]
thx for that insanely fast answer ;)

an AUR package would be awesome, since thats one of the reasons, Arch is so nice.

**Comment by tasn** [comment]
Pleasure. Will really try to get to it. :)

**Comment by tasn** [comment]
It's now available on AUR:

https://aur.archlinux.org/packages/etesync-dav/

**Comment by dwuttke90** [comment]
thx alot man.
