### ISSUE TITLE
Gnome Evolution setup manual

### ISSUE THREAD

**Issue by dilyanpalauzov** [etesync/etesync-dav#130]
https://github.com/etesync/etesync-dav/blob/master/README.md#evolution--gnome-calendar--gnome-contacts rather than repeating the setup for each WwDAV collection, users shall choose as type 'Collection account' once.

**Comment by tasn** [comment]
Thanks for the info! Could you please open a pull-request with the changes? (You can just click the edit button directly from the readme page and then it'll you do it). Would be great if you could get proper credit.

If not, let me know, and I'll do it myself.

Thanks!

**Comment by dilyanpalauzov** [comment]
No, I even do not use EteSync.

**Comment by tasn** [comment]
Ahh, OK, thanks for the info. :)

**Comment by tasn** [comment]
I just tried it, and it doesn't work. No error no nothing. I asked on the #evolution IRC channel, let's see.
Here's what I asked (for reference):

> I'm using radicale as the server and I'm able to add calendars one-by-one (or even use the "find calendar" functionality), but I'm unable to add it as a collection account. When I click "Finish" it just doesn't do anything and doesn't progress. Just stays there. Version of evolution/eds: 3.36.2. I'm on arch. Any ideas?

**Comment by dilyanpalauzov** [comment]
Looks like https://gitlab.gnome.org/GNOME/evolution/-/issues/947.

**Comment by tasn** [comment]
Thanks, I'll add information there.

**Comment by tasn** [comment]
There was an issue upstream which is why I was struggling, but it shouldn't affect most users. I'll fix the README now. Thanks again.

**Comment by dilyanpalauzov** [comment]
See also https://gitlab.gnome.org/GNOME/evolution/-/issues/953.
