### ISSUE TITLE
Latest release is missing the build

### ISSUE THREAD

**Issue by bleetsheep** [etesync/etesync-dav#131]
Previous releases included the built binaries, particularly `linux-etesync-dav` and `linux-etesync-dav.sig`, but the `v0.18.0` release does not. Will they be added? (The [installation instructions](https://github.com/etesync/etesync-dav#installation) also say to use the binaries from the releases page.)

**Comment by tasn** [comment]
I just finished uploading the new binaries. :)
Sorry for the delay, I had an issue with the build.

**Comment by bleetsheep** [comment]
Thanks, my update script works again :)
