### ISSUE TITLE
Error: database is locked

### ISSUE THREAD

**Issue by Zvezdin** [etesync/etesync-dav#132]
I've been running etesync-dav under arch. I don't manually shut it down before I upgrade my system (and hence the etesync-dav AUR package), nor do I do that when I shut down my computer.

It has already happened a few times that I find etesync-dav to be stuck and unable to sync with my local frontend. I don't remember if the error immediately came after a system reboot or an upgrade, but I suspect that it has. The error appears after etesync is started and a frontend tries to sync with it. The message is:
`An exception occurred during REPORT request on LOCALHOSTURL: database is locked`

I've tried restarting the systemd service multiple times but it is still stuck there.

I've started a new issue instead of updating #116 as the symptoms and error message I receive are different, and perhaps the same problem is triggered by a different stimuli here.

**Comment by Zvezdin** [comment]
Update: For my case the problem has resolved itself by simple time (upon the latest restart, etesync-dav gave the error, and after a few other attempts at syncing to it without restarting to it, it started working). However I think that it's still worth to explore what is the case of this.

**Comment by tasn** [comment]
Glad to hear it fixed itself for you. I guess you're running the latest version, 0.18.0?
I really have no idea why it would get stuck, but we definitely need to investigate it. I once got the "DB is locked" error, but it went away after restarting etesync-dav and never showed itself again. No clue what caused it.

**Comment by Zvezdin** [comment]
I was running 0.17.1-1, just upgraded to 0.18.0-1. Restarting the systemd service after the update does not seem to cause the error. Given that it's a rare occurrence I'll watch carefully how it runs in the next couple of days. Perhaps the reason why we don't notice it much is if it happens for a short period of time before it somehow fixes itself.

**Comment by tasn** [comment]
This sounds like a plausible explanation of what's going on. Please keep an eye out.
