### ISSUE TITLE
iOS Guide: Please be more clear about the order of the steps and any prerequisites

### ISSUE THREAD

**Issue by porg** [etesync/etesync-dav#139]
https://www.etesync.com/user-guide/ios/

As of now is in this order:
On the very top:
0: Install the EteSync app from the App Store
Followed by these chapters:
1: Syncing without iCloud
1a: Recommended: turning iCloud off
1b: DAV account workaround (keeping iCloud on)

If one wants variant 1b, then you first have to prepare this barebone CalDAV account, then install the app and run it's initial setup wizard.

Otherwise the barebone CalDAV account is not available for choice in the wizard. And the user will utterly fail. Was the case for myself.

Please very explicitly mention the chronology of what needs to happen when in order to work correctly.

**Comment by tasn** [comment]
This seems like the wrong repo for this, could you please re-open this ticket in the ios repo: https://github.com/etesync/ios

Thanks!
