### ISSUE TITLE
Add task support

### ISSUE THREAD

**Issue by dwuttke90** [etesync/etesync-dav#14]
Hey there,

supporting tasks would be awesome.
atm the tasks get just deleted when syncing. thats evil...

**Comment by tasn** [comment]
Just for reference: this is the relevant task for the Android client: https://github.com/etesync/android/issues/7

Will have to implement in both (and in the web client).

**Comment by dwuttke90** [comment]
as this seems to take a while to implement. any chance to get a faster solution done which lets me at least use tasks locally without getting deleted?

**Comment by tasn** [comment]
I can look into that, though it's very confusing and could lead to data loss if people think they'd be saved, when they aren't. Can't you just tell your client to save tasks locally rather than to server?

**Comment by dwuttke90** [comment]
oh ye,

thx for the answer. actually i didnt think of that possibility... my bad.

**Comment by tasn** [comment]
Maybe one shortcut would be to only implement task support on DAV. This will be much quicker than all platforms, and other platforms don't suffer from the same "tasks disappear" issue.

**Comment by tasn** [comment]
Done. :)
Sorry it took so long...
