### ISSUE TITLE
UX: Encryption setup unclear in linux

### ISSUE THREAD

**Issue by tzugen** [etesync/etesync-dav#144]
Setting up an account in linux:
I am presented with a form with two password fields.
One I know, the encrpytion password is unknown to me.
It looks like the form is asking for something I know, when in fact i am setting up a new encryption password.

### Suggestion:
Break up the process in two parts:
* User logs into account
* Check if encrpytion already setup.
* If yes, ask for enc. password.
* If no, present form to create enc. password (with confirmation field)

**Comment by tasn** [comment]
I think this is now fixed in EteSync 2.0, so closing this.
