### ISSUE TITLE
Etesync DAV bridge sync issue

### ISSUE THREAD

**Issue by zacs86** [etesync/etesync-dav#146]
Good afternoon,

I tried the sync deleting an event (or a contact) from my smartphone but I noticed that the event still remains on Thunderbird (I waited for hours to be sure). How can I do?

Thank you.
Bye.

**Comment by tasn** [comment]
Sorry, I forgot to reply! Could you please try the latest version (0.19.0)? We fixed some related issues there that may be relevant.

**Comment by tasn** [comment]
Seems to be fixed (based on reports from others).
