### ISSUE TITLE
cannot find subtasks?

### ISSUE THREAD

**Issue by SchnozGuy** [etesync/etesync-dav#147]
- no support for subtasks (only checklists)?  
- only support for 1 tag per task?  

just a quick check, and i would be very disappointed if it is true.

**Comment by tasn** [comment]
In etesync-dav subtasks are just sent to DAV clients, so as long as the DAV client supports it, it should work. Some DAV clients, like "Reminders" on macOS (iOS? I don't remember) don't support subtasks when the account is not an iCloud one, though that's a limitation in those clients, not in etesync-dav.

What clients are you using that you are getting this limitation?

**Comment by SchnozGuy** [comment]
im using Tasks for Android. it supports tasks with multiple syncing services (including EteSync), but by comparing my Tasks in the app and Website, it apoears that subtasks are not being saved

**Comment by tasn** [comment]
The website being https://client.etesync.com ? If so, this is the wrong repo, and why I was confused. Could you please open a ticket at: https://github.com/etesync/etesync-web/ ?

Please don't reply here, but in the new ticket, but do they not show when you go to the change list in: Side menu -> Journals -> Your task list -> Change history? Do they not show as tasks at all? Or do they just not show correctly?

**Comment by tasn** [comment]
Moved to https://github.com/etesync/etesync-web/issues/144
