### ISSUE TITLE
Won't run on Windows 7

### ISSUE THREAD

**Issue by cniesen** [etesync/etesync-dav#151]
I was trying to run etesync-dav.exe version 0.20.0 on Windows 7 ~~32bit~~.  The app started, a second process was created and then both processes quietly shut down.  No error messages or error log that I could find.

When running it on Windows 10 64 bit things ran fine.

Is this a 64 bit executable.  If so a note about that in either the readme or the release notes would be nice.

**Comment by tasn** [comment]
Hey,

If an app was started and a second process was created it probably means it's running (so 32bit friendly). I'm not too sure to be honest, as I don't currently have access to my build machine.
I just made a new release which was built an a 64bit machine for sure. I wonder: does that run for you on the Win 7?

**Comment by cniesen** [comment]
Oops, I just noticed that computer runs Windows 7 64 bit not 32 bit.  Sorry about that.  The problem still occurs with etesync 0.20.2.

Anything I can do to trace down the issue? Logs to look at? Things to do?

**Comment by tasn** [comment]
I'm just releasing a new version (0.20.3) that may fix it, please reopen this ticket if it doesn't.

**Comment by cniesen** [comment]
Microsoft Security Essentials doesn't like the 0.20.3 version.  It reports "Trojan:Win32/Zpevdo.B" and removes the executable before I can run it.

**Comment by cniesen** [comment]
> please reopen this ticket if it doesn't.
@tasn I don't have permission to reopen closed issues.

**Comment by cniesen** [comment]
Confirmed, it works now.  BTW, I had to delete the AppData\Local\etesync directory to make it work.

**Comment by tasn** [comment]
Weird. :|
