### ISSUE TITLE
getting 401 http error on  FreeBSD, Archlinux, Fedora and Debian Buster

### ISSUE THREAD

**Issue by Escobar523523** [etesync/etesync-dav#158]
same error on all devices:
Fetching auth token
Traceback (most recent call last):
  File "etesync-dav", line 71, in <module>
  File "etesync-dav", line 50, in manage
  File "etesync_dav/manage.py", line 96, in add
  File "etesync/service.py", line 46, in get_auth_token
etesync.exceptions.HttpException: 401
[8600] Failed to execute script etesync-dav

i followed the install instructions step by step, i tryed the precompiled version, the installation with venv and with pip3
what am i doing wrong? 
anything that would help me get etesync running would be appreciated, thanks

**Comment by tasn** [comment]
Sorry for a configuration change we introduced yesterday, it should now be fixed.

**Comment by tasn** [comment]
Please let me know if it isn't

**Comment by Escobar523523** [comment]
thanks for the quick answer, i was starting to doubt myself allready :-)

**Comment by tasn** [comment]
Haha, glad to see it works. :)
