### ISSUE TITLE
 UNIQUE constraint failed: journalentity.local_user_id, journalentity.uid

### ISSUE THREAD

**Issue by asvc** [etesync/etesync-dav#160]
Subj, Windows 10.0.18363.0,
> Version 0.20.3
> shasum B26801DE587E8EE064A4F2E0B4D0FF2129C3840A

The message is shown after the "Deriving encryption keys, please wait…"

**Comment by asvc** [comment]
Fixed by restarting an app twice and re-submitting the request.

**Comment by tasn** [comment]
Weird, but glad that it fixed itself.
We are overhauling the cache handling of the DAV bridge (the part that errored) as part of etesync 2.0, and this would be different anyway, and probably better/fixed. :)
