### ISSUE TITLE
EteSync 2.0: etesync-dav.exe fails

### ISSUE THREAD

**Issue by cniesen** [etesync/etesync-dav#165]
I downloaded the beta windows EteSync DAV executable from https://stosb.com/~tom/etesync2/etesync-dav.exe

After starting the executable I get a dialog "Fatal error detected" with the message "Failed to execute script etesync-dav" once I click the OK button the two etesync-dav processes terminate.

Let me know if I can find and supply more information for you.

**Comment by cniesen** [comment]
No changes when I renamed the existing AppData\Local\etesync\etesync-dav folder.  The dialog is still shown.  No new AppData\Local\etesync\etesync-dav folder has been created.

**Comment by tasn** [comment]
I haven't fixed the underlying issue yet (still trying to figure out the best way), though I just uploaded a new fixed binary to the same path. Sorry for the trouble!

**Comment by tasn** [comment]
I also fixed the underlying issue now. It was a problem with how we were building the Python etesync v2 library. We essentially used a trick to speed up the builds that worked very well on Linux and macOS, but was failing on Windows because it does things a bit differently.

**Comment by cniesen** [comment]
@tasn Yes, the new download works to an extend.  The etesync-dav server starts up and I can add my account on the server.

However, the initial download of the contacts via the web browser returns an empty My Contacts.vcf and the My Contacts.vcf file only contains
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//PYVOBJECT//NONSGML Version 1//EN
X-WR-CALNAME;VALUE=TEXT:My Calendar
END:VCALENDAR
```
Then when I try to connect via Thunderbird, Thunderbird get the "NS_ERROR_NET_TIMEOUT" error.
After that I get a 500 (internal server error) when I try to follow the "collection list" link via a web browser.

The android app (version 2) downloaded the my calendar entries fine.

**Comment by tasn** [comment]
Grrr, that's not good. :| The annoying thing is that on Windows there's no easy way to get the debug logs. :|
Do you have access to a Linux/mac that you can run `etesync-dav -D` there so we can get the logs? If not, I'll have to try and figure it out.
