### ISSUE TITLE
Associate Account issues with Contacts on macOS

### ISSUE THREAD

**Issue by sohnemann** [etesync/etesync-dav#171]
Hi there,

I have a problem with CardDAV on my Mac. As I'm sharing my EteSync Account with my partner,
her contacts are also in my personal contact list, even though I created two contact lists when setting up EteSync.
I had the same issue on my Android device, but fortunately I was able to hide her contacts from mine.

Is there any way to make sure that the contacts are separated on macOS?

Cheers
sohnemann

**Comment by tasn** [comment]
Hey,

I think this question is better suited for the chat at https://www.etesync.com/community-chat/ so I'm closing this ticket.
Anyhow, regarding your issue: an Associate Account is a fully separate account (with a different email), but it comes with one limitation, associates can't have their own private data, only data shared with them. It sounds to me like you didn't really create an associate account for your parter. If you really did, all you need to do is only share one of the lists with them and only the ones shared will show for them.
If you'd still like to just share an account (which is what you seem to be doing), I bet there's a way on the mac to not show a certain contact list, like you did for Android, though that's a mac specific question and you'll have to check how to do that somewhere mac specific.

I hope this helps.
