### ISSUE TITLE
Evolution Fails to Add and Sync Contacts with v2.0 EteSync Account Added as Collection Account from linux-etesync-dav 0.30.0 

### ISSUE THREAD

**Issue by Gambloide** [etesync/etesync-dav#173]
# Setup
**OS:** `Linux carbon 5.8.15-201.fc32.x86_64 #1 SMP Thu Oct 15 15:56:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
**EteSync DAV:** `0.30.0`
**EteSync Account:** `v2.0` only holding contacts; no calendars, tasks or notes
**Client:** `Evolution/3.36.5`
**Debug Log:** [debug-log.txt](https://github.com/etesync/etesync-dav/files/5395497/debug-log.txt) (generated via `sh -c "./linux-etesync-dav -D" &> debug-log.txt`)

# Steps to Reproduce
1. run `linux-etesync-dav` (v.0.30.0)
1. Set up new local DAV account on `http://localhost:37358/` via EteSync v2.0 account (previously migrated)
1. Follow [steps to set up Evolution](https://github.com/etesync/etesync-dav/tree/v0.30.0#evolution--gnome-calendar--gnome-contacts)

# Expected Result
Evolution shows entries for contacts, calendars and tasks.

# Actual Result
Evolution only shows entries for calendars and tasks, but not contacts.
![etesync-contacts-missing-evolution](https://user-images.githubusercontent.com/5939852/96335276-decc0f80-1077-11eb-9b42-8aee026905bc.jpg)

# Workaround
Setting up the contacts using `File > New > Address Book` in Evolution works.
So it seems one can currently use the `Collection Account` for calendars and tasks and `Address Book` for contacts.
The sync also works both ways in this setup (tested using [web GUI](https://pim.etesync.com/pim/contacts) and GNOME contacts).

# Additional Notes
- Downloading the `Default.vcf` file from `http://localhost:37358/.web/user/<username>` works fine.
The same file can also be successfully imported into Evolution manually.
- The same v2.0 account set up on Android via the APK from https://blog.etesync.com/etesync-2-0-ready-for-testers/ also syncs the same contacts just fine (tested using [web GUI](https://pim.etesync.com/pim/contacts)  and Contacts app on Android)
- The same Evolution client worked fine with a prior version of linux-etesync-dav and a `v1` account. Sadly I don't know the version of the linux-etesync-dav binray anymore and already deleted it.
- The initial `401 Unauthorized` responses in the log are caused by Evolution not giving an option to provide a password before the initial `Look Up` call when adding a new `Collection Account`.

**Comment by tasn** [comment]
Sorry for the slow reply, have been very busy with EteSync 2.0.

Thanks to your detailed report I was able to reproduce it without a problem. I'm not sure what's exactly the cause, but I'm on it.

Interestingly enough, the contacts actually sync after I restarted etesync-dav and just let Evolution try to sync again, so I'm not sure exactly what's going on.

**Comment by tasn** [comment]
Release a new version with the fix. Thanks again for the detailed report, and I wish more reports were like this! :)
