### ISSUE TITLE
docker build: etebase_python.Error: User not found

### ISSUE THREAD

**Issue by y-x41** [etesync/etesync-dav#177]
Hey,

I built a container using the provided Dockerfile. When trying to add a user with `docker run -it --rm -v etesync-dav:/data etesync/etesync-dav manage add USER_EMAIL` and providing the correct password the below error occurs.
This doesn't happen with the image pulled from docker hub. The locally built container seems to run with the data dir from the dockerhub container. Just logging in seems to be the issue, though I haven't investigated much.

```
Please enter the EteSync account password: 
Logging in
Traceback (most recent call last):
  File "/usr/local/bin/etesync-dav", line 84, in <module>
    manage(sys.argv[2:])
  File "/usr/local/bin/etesync-dav", line 63, in manage
    print_credentials(args.username, manager.add_etebase(args.username, password))
  File "/usr/local/lib/python3.9/site-packages/etesync_dav/manage.py", line 164, in add_etebase
    etebase = Etebase.Account.login(client, username, password)
  File "/usr/local/lib/python3.9/site-packages/etebase/__init__.py", line 90, in login
    return cls(etebase_python.Account.login(client._inner, username, password))
etebase_python.Error: User not found
```

**Comment by tasn** [comment]
Are you using a self-hosted server or the hosted one?

**Comment by y-x41** [comment]
The hosted one

**Comment by tasn** [comment]
If you can try to sniff your traffic (or e.g. use `mitmproxy`) to see why it's failing, that would be great.

Another thing, does it work when you use the web management UI?

**Comment by tasn** [comment]
To anyone who may find this later on:
The issue was that @y-x41 was trying to add his EteSync 1.0 through the EteSync 2.0 "add account" menu. 
The reason why it worked for him on the published docker image is because he already had his credentials set there.
