### ISSUE TITLE
Provide Linux build for ARM processors (aarch64)

### ISSUE THREAD

**Issue by MorgothSauron** [etesync/etesync-dav#184]
I was trying to setup etesync-dav using docker on a Pi4 (aarch64) but I realized that the build you provide is for AMD64. I'll probably be able to build etesync-dav to use it, but it would be good if a build for ARM was available.

os: Ubuntu 20.04.1 LTS
cpu architecture: aarch64

**Comment by tasn** [comment]
Should be fixed now with the latest version. Please let me know if it's indeed the case.

**Comment by MorgothSauron** [comment]
That was fast.

The binary does run on Ubuntu 20.04.1 LTS on Pi4 without issue. 

However I can't get it to work in docker

- alpine 3.12 (with `libc6-compat` installed)

```
Error relocating /bin/linux-arm64-etesync-dav: __realpath_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __memcpy_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __snprintf_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __vsnprintf_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __strcpy_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __vfprintf_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __fprintf_chk: symbol not found
Error relocating /bin/linux-arm64-etesync-dav: __strcat_chk: symbol not found
```

- debian:buster and ubuntu:20.04

```
Traceback (most recent call last):
  File "etesync-dav", line 101, in <module>
OSError: [Errno 29] Illegal seek
[6] Failed to execute script etesync-dav
```

I used `ldd` to check the object details and I can't see any outstanding dependency.

**Comment by tasn** [comment]
Alpine not working: maybe the libc6-compat isn't complete? Not sure.
Debian in docker: no idea, though it looks like it's just failing in a python function. Could be a libc conflict but could also just be something with how you setup the docker image.

For whatever it's worth, there's a Dockerfile in this repo, and it's recommended to just run the Python code itself, rather than the pre-compiled binaries, in docker. Dockerfile: https://github.com/etesync/etesync-dav/blob/master/Dockerfile

**Comment by MorgothSauron** [comment]
I'll do more tests to try to find why it is not working in docker. It's a bit surprising that it fails with the official ubuntu:20.04 image because I do run Ubuntu 20.04 on the host. 

> For whatever it's worth, there's a Dockerfile in this repo, and it's recommended to just run the Python code itself, rather than the pre-compiled binaries, in docker. Dockerfile: https://github.com/etesync/etesync-dav/blob/master/Dockerfile

For now this is what I'm doing so I can have something to use with Thunderbird. But in the end it will be better if I can make it work with the binary. With the binary the docker image would be much faster to build. I could run the binary on the host directly but I prefer to isolate every components I host in a container.

I'll open a new issue once I have more details on this.

**Comment by tasn** [comment]
There are more lightweight ways to isolate applications, such as `firejail`. But sure, I get what you are trying to do.

Let me know.

**Comment by julianfairfax** [comment]
How come some builds include the arm64 version and others don't?

**Comment by tasn** [comment]
If memory serves: we used to build an travis-ci which supported ARM, and when we migrated Github actions didn't support ARM yet, at least not how we were using it.

**Comment by julianfairfax** [comment]
The good news is: you can just use the package from PyPI on an ARM device with no issue! You will however have to manually download and modify the systemd service, which I have done like this on my PinePhone running Mobian Linux:
```
curl -L -s -o ~/.config/systemd/user/etesync-dav.service https://github.com/etesync/etesync-dav/raw/master/examples/systemd-user/etesync-dav.service
sed -i 's/usr\/bin/home\/mobian\/.local\/bin/' ~/.config/systemd/user/etesync-dav.service
```
