### ISSUE TITLE
cert-gen exception due to ca=False change

### ISSUE THREAD

**Issue by AezNwBrZ6** [etesync/etesync-dav#186]
Apologies! I believe it's caused by a bug I introduced in https://github.com/etesync/etesync-dav/issues/181

etesync-dav cert-gen
dusage: radicale [OPTIONS]
etesync-dav: error: unrecognized arguments: cert-gen

`basic_contraints = x509.BasicConstraints(ca=False, path_length=0)` is incorrect. 
I believe path_length=None or perhaps the argument should be entirely omitted depending the library you're using

I believe this is the reason for the exception and I will regenerate cert to check once a new build is released. Again, apologies!

**Comment by tasn** [comment]
It's `etesync-dav certgen` without the dash. Does that still not work? What makes you think it was the change in #181?

**Comment by tasn** [comment]
Ah actually, I just tested it myself, and that part is indeed also wrong, fixing ow!
