### ISSUE TITLE
Hosted DAV Adapter gives 500

### ISSUE THREAD

**Issue by BrechtSerckx** [etesync/etesync-dav#195]
When trying to re-enable the Hosted DAV adapter after migrating to V2, it gives a 500.

Steps taken:
1. Go to the [Hosted DAV Adapter](https://dashboard.etebase.com/user/partner/etesync/hosted-dav/)
2. Click `Enable`
3. Wait a bit
4. An error is displayed: `500 Server Error: Internal Server Error for url: https://dav.etesync.com/api/v1/creds/`

Browser: Firefox 78
OS: Linux/NixOS 20.03
User-Agent: `Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0`

**Comment by tasn** [comment]
@stefanschramek sounds like #187 maybe. What you can do is disable and re-enable the DAV adapter which will wipe the  DAV user's data and let you start again.
