### ISSUE TITLE
macos instructions link on EteSync DAV Management page is broken

### ISSUE THREAD

**Issue by alanruttenberg** [etesync/etesync-dav#197]
broken link: https://github.com/etesync/etesync-dav/blob/master/macos-instructions.md
should it be instead https://github.com/etesync/etesync-dav/wiki/MacOS-instructions ?

**Comment by Salt-Factory** [comment]
Hi @alanruttenberg, you should indeed refer to the wiki link for the correct instructions.
However, I cannot find the broken link in the README. 
Is it possible that you are using an older version of the README (from more than 7 days ago)? 
The link was only recently changed to point to the wiki.

**Comment by alanruttenberg** [comment]
It looks like the sort-of duplicate is from an entry that I added then edited. When I search on android I only see the current version. In looking at the log, I see two entries, one for the original, and one for the edited. Is the web app perhaps considering those to both be valid and distinct entries, by chance?

**Comment by alanruttenberg** [comment]
Another clue on the sort-of duplicate: The most recent version has a UID but the older on does not.

**Comment by Salt-Factory** [comment]
Thanks, I changed the dead link. 

Could you open up a new issue describing your problem? Otherwise it will get buried here.

**Comment by alanruttenberg** [comment]
I split out the other two issues. Closing this one.
