### ISSUE TITLE
missing dependency on pytz to avoid: ERROR:root:No module named 'pytz'

### ISSUE THREAD

**Issue by stuart12** [etesync/etesync-dav#20]
On Debian unstable, I did
```
python3.6 -m venv etesync-dav
source etesync-dav/bin/activate
pip3 install etesync-dav
etesync-dav
```
and when I tried to validate a new remote address book with CardBook got a stream of messages `ERROR:root:No module named 'pytz'`. I had to do `pip install pytz` to get `etesync-dav` not to throw this error.

**Comment by tasn** [comment]
Thanks for the report. I wonder what needs it and why it wasn't pulled in. FWIW, it's not installed here, and it works for me.

I need to bump the deps anyway (and verify things work), so I'll also add it while at it.

Thanks!

**Comment by tasn** [comment]
Just checked again with a fresh install, and I still don't have pytz installed. I really have no idea where this is coming from.

**Comment by tasn** [comment]
Updated all the deps, maybe that will solve it for you? Though I still see no pytz.

**Comment by tasn** [comment]
Can you maybe also try running etesync-dav with -D? It should at least show where this error is coming from (hopefully).

**Comment by tasn** [comment]
All of a sudden it started happening here too... I'll fix it soon. :)
Sorry for the crazy long delay.

**Comment by tasn** [comment]
It's not yet available in the binary builds, but will be available for people getting from pypi or docker.

**Comment by stuart12** [comment]
hi, I'm sorry that I wasn't responsive to your questions but at least you had some context when the problem happened to you.  I suppose that I should remove `pytz` from [etesync-dav@.service](https://github.com/etesync/etesync-dav/blob/master/examples/systemd-sandbox/etesync-dav%40.service). Thanks for the fix and for etesync.

**Comment by tasn** [comment]
You provided enough information, I was just trying to figure out why it was happening.
If you can, please open a PR for the service file, but if you don't have the time, no worries, as it doesn't change anything (it's just explicitly installing pytz instead of implicitly).
