### ISSUE TITLE
Self-signed SSL certificate doesn't work;  happens only in EteSync DAV Management WebUI

### ISSUE THREAD

**Issue by msbavaria** [etesync/etesync-dav#208]
EteSync DAV version:  0.30.7
Radicale version:  3.0.3

- My EteSync server is running locally at LOCAL_IP:443.
- I have my own CA and imported it successfully on the computer I'm trying to use the EreSync DAV bridge on. 
- `curl https://LOCAL_IP/ --cacert caroot.pem` returns the proper website and Firefox shows me that the website is from a trusted certificate authority.

When I try to add a user in the EteSync DAV Management WebUI at `locahost:37358`, it always returns: 
`error sending request for url (https://LOCAL_IP/api/v1/authentication/login_challenge/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (self signed certificate)`

I also tried using the options listed at https://github.com/etesync/etesync-dav/blob/master/README.md#self-signed-certs.

Nothing works.

**Comment by msbavaria** [comment]
I want to add: I have no issue connecting to my server and logging in if I use the web client at https://pim.etesync.com/.

**Comment by msbavaria** [comment]
I managed to fix the issue and it is not related to EteSync. 

If anyone has the same issue: Please make sure to set up your SSL certificates correctly. In my case I needed to put my LOCAL_IP in the SubjectAltName field in my OpenSSL configuration file that was being used to create the SSL certificates, e. g. SubjectAltName = IP:LOCAL_IP.

**Comment by tasn** [comment]
Great to hear!
