### ISSUE TITLE
'well-known' error prevents starting server

### ISSUE THREAD

**Issue by patogit** [etesync/etesync-dav#21]
Setting up on Manjaro Linux (Arch derivative), followed instructions in readme, got an error.

```
[user@system ~]$ etesync-dav-manage add me@email.net
Please enter the EteSync login password: 
Please enter your encryption password: 
Fetching auth token
Deriving password
Saving config
User: me@email.net
Password: letters-and-numbers
[user@system ~]$ etesync-dav
ERROR: Invalid configuration: Invalid section 'well-known' in config
[user@system ~]$ etesync-dav
ERROR: Invalid configuration: Invalid section 'well-known' in config
[user@system ~]$ 
```
Here are the contents of `radicale.conf`:
```
[server]
hosts = localhost:37358

[auth]
type = htpasswd
htpasswd_filename = /home/user/.config/etesync-dav/htpaswd
htpasswd_encryption = plain

[storage]
type = radicale_storage_etesync
database_filename = /home/user/.config/etesync-dav/etesync_data.db
remote_url = https://api.etesync.com/
credentials_filename = /home/user/.config/etesync-dav/etesync_creds

```

System updated two days ago.

Any hints?

Looking forward to this working!

**Comment by tasn** [comment]
Are you using the aur package? If so, what version of radicale do you have? I'd unfortunately had issues with newer versions of radicale. I'm still looking into that, but until then, you'd probably want to install using the docker installation or into a virtualenv.

**Comment by tasn** [comment]
Hm... I actually updated the deps now to the latest radicale and it seems to be working great. Not sure what your problem is.

**Comment by patogit** [comment]
I'm using the AUR package, with Radicale version 2.1.9-2. 

Docker install didn't work. I don't know how to install into a virtualenv.

**Comment by tasn** [comment]
virtualenv:
```

pacman -S python-virtualenv
virtualenv venv
source venv/bin/activate
pip install etesync-dav
./venv/bin/etesync-dav-manage  # And the rest of the etesync commands
```

**Comment by tasn** [comment]
Oops, I thought I closed this one. It works, right? I assumed #26 fixed it.
