### ISSUE TITLE
Docs should be updated to reflect how to use Thunderbird's new built-in CalDAV / CardDAV capabilities

### ISSUE THREAD

**Issue by Peter4487** [etesync/etesync-dav#258]
As of [Thunderbird 91](https://support.mozilla.org/en-US/kb/new-thunderbird-91) there is native support for CalDAV and CardDAV. How exactly to use it is a bit hard to figure out. Do this:

1. Add a calendar by hitting the "+" symbol in the toolbar that is usually on the left, or right-click for the context menu and select "New Calendar"
2. Select the "On the Network" radio button
3. For Username put the name of your Etesync account
4. For Location head to http://localhost:37358/.web/login/ and log in
5. Then click the link to collection list
6. Then copy the link for the calendar you're trying to add, and put that in for Location
7. Click "Find Calendars"
8. You will see a "Password Required" popup. Enter the password from the Etesync web interface. Go back to http://localhost:37358/.web/ and click the "Copy Password" button
9. Hit Subscribe, you're done

Thanks again for all the great toys tasn!

**Comment by tasn** [comment]
Oh nice, mind opening a PR against the README?

**Comment by sawft99** [comment]
It looks like this was done?

**Comment by tasn** [comment]
Yup, thanks!
