### ISSUE TITLE
Start date removed once tasks.org app syncs if no time specified

### ISSUE THREAD

**Issue by sawft99** [etesync/etesync-dav#265]
OS: Android 12
Task app version: Tasks 12.6.1
Sync service: Etesync with Etesync app 2.2.4

If I create a parent task with any amount of child tasks that only has the day for the start and due date, it will save and show what I put in. However after doing a pull down to refresh, it will remove the start date on the parent task. Example before and after pic. Configuring the task and then refreshing.

![Screenshot_20220410-234321](https://user-images.githubusercontent.com/81699231/162808559-6cdbc173-20c6-47ee-bf58-ca3a82e34385.png)

![Screenshot_20220410-234337](https://user-images.githubusercontent.com/81699231/162808584-5126a0d2-17e0-454c-85ca-d5551a674586.png)

I'm not sure if once it syncs Etesync changes it or something else happens. But once I sync, Etesync still shows this raw info with the due and start date.

![Screenshot_20220410-234257](https://user-images.githubusercontent.com/81699231/162808606-7c4fde56-cd71-414c-996d-843d40038a6a.png)

**Comment by sawft99** [comment]
It looks like this is just a matter of adhering to the standard.

**Comment by tasn** [comment]
:)
