### ISSUE TITLE
Docker radicale not accessible at localhost

### ISSUE THREAD

**Issue by patogit** [etesync/etesync-dav#27]
I followed the instructions for Docker installation and http://localhost:37358/ and http://localhost:37358/me@etesync.com/ (modified for my user) don't work, never load anything.
```
sudo docker build . -t etesync-dav:latest
sudo docker run -it --rm -v etesync:/data etesync/etesync-dav setup
```
Running those commands, I entered my username and access pw and encryption pw, and the command finished successfully, but now how do I access my collections in the web browser?

**Comment by tasn** [comment]
First of all, take a look at the readme, the instructions have been updated.
Regardless, you're missing one command:

  docker run --name etesync-dav -d -v etesync:/data -p 37358:37358 --restart=always etesync/etesync-dav

The above commands are just for setup, this one is for actual running.

I'm closing this one, please let me know if I should reopen.
