### ISSUE TITLE
linux: Error when launching 

### ISSUE THREAD

**Issue by MbappeTNul** [etesync/etesync-dav#272]
I am (a noob) on Ubuntu 18.04.5
With etesync Version 0.31.2

`yb@myname:~/Downloads$ ./linux-amd64-etesync-dav`
`[2022-07-23 18:46:56 +0200] [4594] [CRITICAL] An exception occurred during server startup: Failed to start server [localhost]:37358: [Errno 98] Address already in use`

**Comment by tasn** [comment]
It's exactly what the error says, the address is already in use. It means you already have an instance of etesync dav running.

**Comment by MbappeTNul** [comment]
So, I have to `killall etesync`?

**Comment by tasn** [comment]
not sure that's the right command, maybe `pkill etesync-dav` would work. Depends on a lot of things.
