### ISSUE TITLE
MacOS: EteSync DAV stoped working

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [etesync/etesync-dav#287]
**UPDATED 7.7.2023:**

a lot of the discussion below is about me not using the right password (thx again @jhass),  but now with everything setup correctly it is still not possible to connect the Contacts Account on mac OS 12.1 (MacBook Pro (16-inch, 2019))

I'm using the latest version of ETE Sync 0.31.2, the password from  https://localhost:37358/.web/  but are getting this error:

<img width="413" alt="Screenshot 2023-07-07 at 10 09 32" src="https://github.com/etesync/etesync-dav/assets/1157580/c0e53336-67ca-457a-ba4d-a27144bafe59">

anybody knows about a way to find the root cause of this?

**Original:**

I noticed recently, that my contact sync stopped working on my macOs 12.1 (MacBook Pro (16-inch, 2019)) - I tried today to install the client again, but it does not work. 

The Service is apparently running, but I can neither connect to http://localhost:37358/ anymore. 

My knowledge about this is not too great, but I'd happy to dig into some logs or other means of debugging with some assistance. How can I make it work again?

Thx a lot
Andreas

**Comment by jhass** [comment]
For me the key on 13.4.1 was to include the port in the "Server Address" too, that is make it `https://localhost:37358`. Checking Wireshark it was ignoring the "Port" field and always tried ports `8843` and `443`.

**Comment by Andreas-Schoenefeldt** [comment]
Well, it really broke down - https://localhost:37358/ is available, but:

![Screenshot 2023-07-05 at 15 33 35](https://github.com/etesync/etesync-dav/assets/1157580/917a1ad4-5e7b-4c33-bcc9-2b099a79ff28)

**Comment by jhass** [comment]
Ah, I did use the "Advanced" mode with "Server Address" as `https://localhost:37358`, "Server Path" as `/jhass/` and "Port" as `37358`

**Comment by Andreas-Schoenefeldt** [comment]
let me try this tomorrow - thx a lot already for this!  might have screwed up my ssl certs now in the process, maybe I need to wipe it all. I'll report here any outcome.

**Comment by Andreas-Schoenefeldt** [comment]
Unfortunately now luck: I wiped the system of ETE and installed everything fresh (including the certificate) https://localhost:37358/.web/ works just fine, but if I try to add the accounts, I get the same error all over again:

<img width="414" alt="Screenshot 2023-07-06 at 15 18 41" src="https://github.com/etesync/etesync-dav/assets/1157580/5c7e8c2d-11cd-4607-a4fd-ecd82eb63bc1"> <img width="413" alt="Screenshot 2023-07-06 at 15 19 21" src="https://github.com/etesync/etesync-dav/assets/1157580/7e4cc839-0689-4d44-be3f-1ae4beb81563">

Just as a note: it really is the same password, which works for https://localhost:37358/.web/ 

anybody knows about a log location or something, which could give some insight about what is going on? @tasn I know it's annoying, but maybe there is a chance of adding some advice? 

Thx a lot!
Andreas

**Comment by jhass** [comment]
I didn't include the port in the "Server Address" for CalDAV, so that might not work, it did the trick for CardDAV for me.

Remember the password is NOT the one you use to log into https://localhost:37358/.web/, rather it is the one you can copy from there.

**Comment by Andreas-Schoenefeldt** [comment]
Unfortunately also with the password (thx for this btw, I did overlook this detail) from  https://localhost:37358/.web/ and Server Addres without the Port, I still get the same error:

<img width="411" alt="Screenshot 2023-07-07 at 09 59 57" src="https://github.com/etesync/etesync-dav/assets/1157580/ec587be6-0962-43dd-b766-7f063171819f">

The current State is, that I have now no local access to my calendar and contacts anymore. It sadly looks like I have to quit on ETESync - I see no further way for me to make this work.

**Comment by Andreas-Schoenefeldt** [comment]
Uh wait! It just worked, if I put `localhost` without the port and without `https` to the account 🥳 

@jhass - a massive thx to you!

**Comment by Andreas-Schoenefeldt** [comment]
Ok, so the calendar is back again (phew) BUT - Contacts (which I think was also the beginning of this odysee) appear to be really broken. The exact same credentials are not working for the Contacts Account:

<img width="413" alt="Screenshot 2023-07-07 at 10 09 32" src="https://github.com/etesync/etesync-dav/assets/1157580/6394f4c4-5e0c-4dc4-9fbd-15874a8adfd4">

I can live without a Contacts sync to my laptop, but of course it would be great to have it working..

**Comment by jhass** [comment]
So that's what my initial comment was about, MacOS seems to ignore the port setting in the advanced CardDAV setup dialog, but does respect the port for me if I put it into the server address additionally

**Comment by tasn** [comment]
@jhass, yeah, I think this is documented somewhere in the dav docs. macOS is very buggy, and there are a few quirks with the system. This is one of them.

**Comment by Andreas-Schoenefeldt** [comment]
Friends, it worked with the quirks described above. Thank you for helping me with that and sorry for the drama and back & forth on this. I'll review the MAC documentation and see if it can be made even clearer for people not familiar with the matter like myself.

**Comment by tasn** [comment]
Please make suggestions if you see anything, thanks! I'm closing this ticket as it seems to be fixed.

I tried reporting this bug (among others) to Apple years ago, but they are not very responsive.

**Comment by Andreas-Schoenefeldt** [comment]
Thank you, I changed a bit the instructions: https://github.com/etesync/etesync-dav/wiki/MacOS-instructions not sure if it needs to be approved, to me it looked like it went through just like this.
