### ISSUE TITLE
Native Thunderbird add-on?

### ISSUE THREAD

**Issue by bam80** [etesync/etesync-dav#3]
Hi, thank you for a great project!
I wonder if native Thunderbird add-on ever considered? Maybe one based on CardBook add-on..
It would allow to not having to run a separate compatibility layer(server) between EteSync and Thunderbird.

**Comment by tasn** [comment]
Hey,

Great idea! To be honest I never even considered this option, but would definitely work.

The only problem is that I have limited time and we have limited resources, and we really can't spare the time to undertake such a project. The other issue is that now if the cardbook developers improve the addon, we benefit from that too, if we fork it, it'll again add even more work. Maybe we can send patches and add EteSync support to CardBook directly. That would probably work best.

Maybe consider opening a ticket with cardbook?

I'm leaving this ticket open because I'll happily help anyone who wants to undertake this task.

**Comment by bam80** [comment]
I agree adding functionality to existing add-on would be better than forking it, but I just don't know how much similarities with WebDAV the EteSync's protocol has, to be based on CardBook.
Also, some people look pessimistically to creating security features on top of WebDAV:
>[WebDAV was the wrong choice](https://gist.github.com/rhodey/873ae9d527d8d2a38213#webdav-was-the-wrong-choice)

But if WebDAV already is a base of EteSync project, I guess we have no choice on this stage anyway..

**Comment by tasn** [comment]
WebDAV is not at the base of the EteSync project, but rather a very simple immutable change-journal and a few operations for manipulating it. See at #4 I further clarified this confusion.

See the journal-manager repo for the server implementation, and the Android, python-api and etesync-web ones for different client implementations.

**Comment by bam80** [comment]
Thanks Tom. Well, maybe it is a good thing that EteSync is not based on WebDAV and doesn't suffer from problems Flock had. On the other hand, it may mean it is not worth trying to base native EteSync Thunderbird add-on on CardBook, which is solely CardDAV oriented. I'm not familiar with internal structure of both projects, so it's just a guess..

**Comment by tasn** [comment]
Maybe it is, maybe it isn't. I'm not familiar with the cardbook source code, but DAVdroid was DAV only, and I still managed to salvage a lot of the code to be used for the etesync android client. Who knows.

**Comment by CardBook** [comment]
Hi folks

of course if I may help for the etesync support, it would be a pleasure... but CardBook is only CardDAV oriented, so I haven't any idea on how difficult this task would be....

**Comment by bam80** [comment]
EteSync <-> CardBook bridge already exists - it's this [etesync-dav](https://github.com/etesync/etesync-dav) service. The task looks to me just to integrate it to the CardBook add-on.
Maybe @tasn will say better.

**Comment by tasn** [comment]
@CardBook, I know nothing about writing plugins for Thunderbird, though I do have a couple of questions:
1. Are plugins written (or can be written) using js?
2. In cardbook: is the dav access abstracted? Or are there calls for dav functions all over the plugin?

As I said, I don't have time at the moment to focus on a native thunderbird plugin, though I think it's a great idea and happy to support whoever undertakes it. It looks like @CardBook may also help, so we got both sides of the story covered.

**Comment by CardBook** [comment]
1/ CardBook is written in javascript
2/ all files are in clear and all dav requests are in the file cardbookSynchronization.js

**Comment by tasn** [comment]
Thanks! Those are great news because there's already a javascript library for EteSync, and obviously having all of the dav specific code in one place will make it easily replaceable.

**Comment by plague-doctor** [comment]
Guys, I hope it will not be considered a necromancy to write in here, but there is an excellent `DAV-4-TbSync` (https://github.com/jobisoft/DAV-4-TbSync) which I use to ete-sync contacts and calendars synced with my Thunderbird. I self host etesync with etesync-dav.
This combo works great but I get this error while synchronizing an AddressBook:
```
URL:
https://etesync-dav.<my-domain>/<my-account>/c7395195582<...>72ceea629da9640/ (REPORT)

Request:
<d:sync-collection xmlns:d="DAV:"><d:sync-token>http://radicale.org/ns/sync/2e138cc284a8<...>202b24016bd</d:sync-token><d:sync-level>1</d:sync-level><d:prop><d:getetag/></d:prop></d:sync-collection>

Response:
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:">
<valid-sync-token />
</error>
```
The synchronization works, all my contacts are synchronizing fine both ways, but this strange error comes up every time...
Any idea why it tries to get the token from `http://radicale.org`? Should I reconfigure something on my etesync-dav? @tasn, any insides?

**Comment by tasn** [comment]
It's not really the right ticket to talk about this, so if you have anything else to say on the topic please open a new ticket, though to answer your question:

EteSync-DAV doesn't implement sync-token support at the moment. For all I know, it's legal in the spec not to, and clients should just ignore it, though it seems like TbSync doesn't silently ignore it as it should and like all the rest of the clients. You haven't misconfigured anything, it's just not yet implemented. Feel free to open a ticket about implementing sync token support if you'd like.

**Comment by tasn** [comment]
I'm closing this because there's already one in the works by the creator of TbSync.
Code will be pushed to https://github.com/etesync/EteSync-4-TbSync as progress is made.
