### ISSUE TITLE
Where to get the password that etesync-dav requires when adding an account?

### ISSUE THREAD

**Issue by devurandom** [etesync/etesync-dav#301]
When I navigate to http://localhost:37358/.web/add/ in my browser, I am being asked for a "username" and an "account password". I do have a password from long ago, but when I enter it etesync-dav responds with `NotFound` without any further explanation:
![image](https://github.com/etesync/etesync-dav/assets/63082/8bf6e194-c36a-41da-8d4c-2f4a355cd39c)

`journalctl -f -b -u etesync-dav`  does not show anything apart from the startup message:
```
Started etesync-dav - A CalDAV and CardDAV adapter for EteSync.
```

In case I have a wrong password I wanted to reset it, but I cannot find any option to do that on https://dashboard.etebase.com/user/partner/dashboard/

In addition, when I navigate to https://www.etesync.com/ and click the "Log In" button in the top right, I am being taken to https://dashboard.etebase.com/user/partner/login/ which does not offer any way to log in using a password. I can log in fine using the "Login via email" button, entering my email address and pressing "send link. But this option does not exist when using etesync-dav and trying to add an account via http://localhost:37358/.web/add/.

I am running NixOS 23.05.20230819.4cdad15 which provides etesync-dav 0.32.1, cf. https://search.nixos.org/packages?channel=23.05&show=etesync-dav&from=0&size=50&sort=relevance&type=packages&query=etesync-dav.

Where do I get this password from and how can I change it?

**Comment by devurandom** [comment]
The readme says:
```md
# Configuration and running

1. Run `etesync-dav` and open the management UI in your browser: http://localhost:37358/
2. Add your EteSync user through the web UI.
3. Copy the DAV specific password by click the "Copy Password" button next to your newly added username.
```

But it does not say where the credentials for step 2 come from.

**Comment by tasn** [comment]
Your normal etesync credentials.

**Comment by tasn** [comment]
I'm closing it, as it's resolved. Though let me know if it doesn't fix it for you.

Btw, mind opening a PR on the README to clarify that it should be your normal etesync credentials?

**Comment by devurandom** [comment]
Are "normal etesync credentials" the ones I use on https://pim.etesync.com/ ? I don't normally visit that page and the dashboard I usually interact with (https://dashboard.etebase.com/user/partner/login/) does not have any credentials and does not allow me to change them. That's what confused me.

**Comment by tasn** [comment]
The normal is pim.etesync.com, yeah. Also what you'd use in the apps for example.

**Comment by devurandom** [comment]
FYI: The error message `NotFound` that I go earlier (cf. description and screenshot of original report, above) was caused by NixOS using the wrong default API URL (cf. https://github.com/NixOS/nixpkgs/issues/251635#issuecomment-1888755886). Once I changed it to `https://api.etebase.com` I could log in.
