### ISSUE TITLE
Errors 403 and 404 using EteSync DAV bridge on eM-client on Windows

### ISSUE THREAD

**Issue by x90125** [etesync/etesync-dav#307]
Hi all.

I'm on Win7 x64 and I have 3 collections (1 address book and 2 calendars).

Although EteSync DAV Bridge works, it's very slow to synchronise and I see a **red question mark** next to the account in eM-Client,
So I enabled logging and found a number of 403 errors...

I replaced my personal data with "HIDDEN" below.  I also omitted all the successful synchronisations (status 200) for the sake of legibility.

Can anyone tell me what's going on?
Thanks.

M..T

**LOG EXCERPT**

eM Client 9.2.2230+82bdd8974c (Windows)
Account's UID is (HIDDEN)
AccountBase.ChangeOnlineState : State changed to ONLINE due User

Request:
Method: PROPFIND, RequestUri: '(HIDDEN)', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept: text/xml
  Brief: t
  Depth: 1
  User-Agent: eMClient/9.2.2230.0
  Content-Type: text/xml; charset=utf-8
}
<?xml version="1.0" encoding="utf-8"?><D:propfind xmlns:D="DAV:"><D:prop><D:getetag /><D:getcontenttype /></D:prop></D:propfind>

Response:
StatusCode: 207, ReasonPhrase: 'Multi-Status', Version: 1.0, Content: System.Net.Http.DecompressionHandler+GZipDecompressedContent, Headers:
{
  Date: Tue, 13 Feb 2024 17:40:58 GMT
  Server: WSGIServer/0.2 CPython/3.8.10
  DAV: 1, 2, 3, calendar-access, addressbook, extended-mkcol
  Content-Type: text/xml; charset=utf-8
}
<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:"><response><href>(HIDDEN)</href><propstat><prop><getetag /><getcontenttype /></prop>**<status>HTTP/1.1 404 Not Found</status></propstat></response><response><href>(HIDDEN)</href><propstat><prop>**<getetag>"GqaLSV5MWAnVigNit8cdBsSgeIfGKRW2"</getetag><getcontenttype>text/vcard</getcontenttype></prop><status>HTTP/1.1 200 OK</status></propstat></response><response><href>(HIDDEN)</href><propstat><prop><getetag>"4gcI5tE3as5bBUoxYM7nylYArMvlLvIs"</getetag><getcontenttype>text/calendar</getcontenttype></prop><status>HTTP/1.1 200 OK</status></propstat></response><response><href>(HIDDEN)</href><propstat><prop><getetag>"hzkgjkfDO5PobbPDfyQFxNHHqPgL8eVQ"</getetag><getcontenttype>text/calendar</getcontenttype></prop><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>

Response:
**StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.0, Content:** System.Net.Http.DecompressionHandler+GZipDecompressedContent, Headers:
{
  Date: Tue, 13 Feb 2024 17:40:59 GMT
  Server: WSGIServer/0.2 CPython/3.8.10
  Content-Type: text/xml; charset=utf-8
}
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:"><supported-report /></error>

Request:
Method: REPORT, RequestUri: '(HIDDEN)', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept: text/xml
  Brief: t
  Depth: 0
  User-Agent: eMClient/9.2.2230.0
  Content-Type: text/xml; charset=utf-8
}
<?xml version="1.0" encoding="utf-8"?><C:addressbook-multiget xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop xmlns:D="DAV:"><D:getetag /><C:address-data /></D:prop><D:href xmlns:D="DAV:">(HIDDEN)</D:href></C:addressbook-multiget>

Response:
**StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.0, Content:** System.Net.Http.DecompressionHandler+GZipDecompressedContent, Headers:
{
  Date: Tue, 13 Feb 2024 17:40:59 GMT
  Server: WSGIServer/0.2 CPython/3.8.10
  Content-Type: text/xml; charset=utf-8
}
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:"><supported-report /></error>

Request:
Method: REPORT, RequestUri: '(HIDDEN)', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept: text/xml
  Brief: t
  User-Agent: eMClient/9.2.2230.0
  Content-Type: text/xml; charset=utf-8
}
<?xml version="1.0" encoding="utf-8"?><C:calendar-multiget xmlns:C="urn:ietf:params:xml:ns:caldav"><D:prop xmlns:D="DAV:"><D:getetag /><C:calendar-data /></D:prop><D:href xmlns:D="DAV:">(HIDDEN)</D:href><D:href xmlns:D="DAV:">(HIDDEN)</D:href></C:calendar-multiget>

Response:
**StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.0, Content:** System.Net.Http.DecompressionHandler+GZipDecompressedContent, Headers:
{
  Date: Tue, 13 Feb 2024 17:41:21 GMT
  Server: WSGIServer/0.2 CPython/3.8.10
  Content-Type: text/xml; charset=utf-8
}
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:"><supported-report /></error>

Request:
Method: REPORT, RequestUri: '(HIDDEN)', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept: text/xml
  Brief: t
  Depth: 0
  User-Agent: eMClient/9.2.2230.0
  Content-Type: text/xml; charset=utf-8
}
<?xml version="1.0" encoding="utf-8"?><C:addressbook-multiget xmlns:C="urn:ietf:params:xml:ns:carddav"><D:prop xmlns:D="DAV:"><D:getetag /><C:address-data /></D:prop><D:href xmlns:D="DAV:">(HIDDEN)</D:href></C:addressbook-multiget>

Response:
**StatusCode: 403, ReasonPhrase: 'Forbidden', Version: 1.0, Content:** System.Net.Http.DecompressionHandler+GZipDecompressedContent, Headers:
{
  Date: Tue, 13 Feb 2024 17:41:21 GMT
  Server: WSGIServer/0.2 CPython/3.8.10
  Content-Type: text/xml; charset=utf-8
}
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:"><supported-report /></error>

SynchronizeItemsCommand finished on ( HIDDEN )
AccountBase.ChangeOnlineState : State changed to OFFLINE due ApplicationShutdown

**Comment by kiber-io** [comment]
@x90125 Hey!
Were you able to solve the problem? I'm getting the same 403 error and I have no idea what's causing it anymore.
