### ISSUE TITLE
etesync-dav stopped working after python 3.12 upgrade (Arch Linux)

### ISSUE THREAD

**Issue by paapereira** [etesync/etesync-dav#311]
Hello, I believe the python upgrade is to blame.
I don't know if a etesync fix for python 3.12 is needed or if this is a OS issue.
Appreciate the help.

``
`$ uname -a
Linux tardis 6.8.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000 x86_64 GNU/Linux

$ pacman -Q python          
python 3.12.3-1

$ pacman -Q etesync-dav     
etesync-dav 0.32.1-3

$ etesync-dav
❯ Traceback (most recent call last):
  File "/usr/bin/etesync-dav", line 10, in <module>
    from etesync_dav.manage import Manager
  File "/usr/lib/python3.12/site-packages/etesync_dav/manage.py", line 21, in <module>
    import etesync as api
ModuleNotFoundError: No module named 'etesync'
````

**Comment by Xiretza** [comment]
If you built a python package against one python version, you'll have to rebuild it against the new python version once it's out. This has nothing to do with upstream.

**Comment by tasn** [comment]
What @Xiretza said. :)
