### ISSUE TITLE
raise RuntimeError("SSL handshake failed: %s" % e) from e

### ISSUE THREAD

**Issue by nephaste** [etesync/etesync-dav#32]
Hi thanks for this project

I am trying to build this for Qnap NAS 

but falling into an error when starting hope you can help me to find out the problem

[~] # /opt/EteSync/bin/python /opt/EteSync/bin/etesync-dav-manage add me@etesync.com
Traceback (most recent call last):
  File "/opt/EteSync/bin/etesync-dav-manage", line 4, in <module>
    __import__('pkg_resources').run_script('etesync-dav==0.1.6', 'etesync-dav-manage')
  File "/opt/EteSync/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/EteSync/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/opt/EteSync/lib/python2.7/site-packages/etesync_dav-0.1.6-py2.7.egg/EGG-INFO/scripts/etesync-dav-manage", line 30
    print("{}:{}".format(name, password), file=f)
                                              ^
SyntaxError: invalid syntax
`
even starting
`[~] # /opt/EteSync/bin/python /opt/EteSync/bin/etesync-dav-manage
Traceback (most recent call last):
  File "/opt/EteSync/bin/etesync-dav-manage", line 4, in <module>
    __import__('pkg_resources').run_script('etesync-dav==0.1.6', 'etesync-dav-manage')
  File "/opt/EteSync/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/EteSync/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    script_code = compile(script_text, script_filename, 'exec')
  File "/opt/EteSync/lib/python2.7/site-packages/etesync_dav-0.1.6-py2.7.egg/EGG-INFO/scripts/etesync-dav-manage", line 30
    print("{}:{}".format(name, password), file=f)
                                              ^
SyntaxError: invalid syntax
`
I am lost thanks for your help

i am using latest Python 2.7.15 

`[~] # /opt/EteSync/bin/pip list
Package                  Version
------------------------ ---------
appdirs                  1.4.3
asn1crypto               0.24.0
certifi                  2018.8.24
cffi                     1.11.5
chardet                  3.0.4
coverage                 5.0a2
cryptography             2.3.1
enum34                   1.1.6
etesync                  0.5.4
etesync-dav              0.1.6
furl                     1.2.1
idna                     2.7
ipaddress                1.0.22
lxml                     4.2.4
netifaces                0.10.7
orderedmultidict         1.0
packaging                17.1
peewee                   2.10.2
pip                      18.0
py                       1.6.0
pyasn1                   0.4.4
pycparser                2.18
pycrypto                 2.6.1
pycurl                   7.43.0.2
pyOpenSSL                18.0.0
pyparsing                2.2.0
pyscrypt                 1.6.2
python-dateutil          2.7.3
Radicale                 2.1.10
radicale-storage-etesync 0.1.6
requests                 2.19.1
setuptools               39.0.1
six                      1.11.0
urllib3                  1.23
vobject                  0.9.6.1
`

I have really no clue how to fix this

**Comment by nephaste** [comment]
just saw in my compilation event

`Installed /opt/EteSync/lib/python2.7/site-packages/appdirs-1.4.3-py2.7.egg
Searching for Radicale>=2.1.10
Reading https://pypi.python.org/simple/Radicale/
Downloading https://files.pythonhosted.org/packages/2c/cd/25145d5042433b60b3aee32206488a074b9d9a7841b399bbd5efda14ecd6/Radicale-2.1.10.tar.gz#sha256=d5c60b57ddc233fce426430710a3c521c7ffd5a0f05b02d2d4ce6f6631194832
Best match: Radicale 2.1.10
Processing Radicale-2.1.10.tar.gz
Writing /tmp/easy_install-lbgIJ_/Radicale-2.1.10/setup.cfg
Running Radicale-2.1.10/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lbgIJ_/Radicale-2.1.10/egg-dist-tmp-dog_I5
  File "build/bdist.linux-x86_64/egg/radicale/auth.py", line 83
    (auth_type, e)) from e
                       ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/config.py", line 231
    "Failed to load config file %r: %s" % (path, e)) from e
                                                        ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/xmlutils.py", line 268
    nonlocal matched
                   ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/__init__.py", line 197
    raise RuntimeError("SSL handshake failed: %s" % e) from e
                                                          ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/web.py", line 62
    (web_type, e)) from e
                      ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/rights.py", line 72
    (rights_type, e)) from e
                         ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/log.py", line 59
    "%s" % (filename, e)) from e
                             ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/storage.py", line 110
    (storage_type, e)) from e
                          ^
SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/radicale/__main__.py", line 95
    print("ERROR: Invalid configuration: %s" % e, file=sys.stderr)
                                                      ^
SyntaxError: invalid syntax

zip_safe flag not set; analyzing archive contents...
Moving Radicale-2.1.10-py2.7.egg to /opt/EteSync/lib/python2.7/site-packages
Adding Radicale 2.1.10 to easy-install.pth file
Installing radicale script to /opt/EteSync/bin

`

**Comment by tasn** [comment]
Hey,

You need python 3. Python 2 is not supported. Please let me know if the problem persists with Python 3.

**Comment by nephaste** [comment]
thanks i will recompile it then.. it was not indicated on github page that we must use Python3

**Comment by tasn** [comment]
Oops, added a note (thanks!).
