### ISSUE TITLE
The Latest Release Lacks Binaries

### ISSUE THREAD

**Issue by deron-dev** [etesync/etesync-dav#329]
Release 0.33.0 does not have binaries in the assets.

https://github.com/etesync/etesync-dav/releases/tag/v0.33.0

**Comment by tasn** [comment]
Yeah, the build was acting up, see https://github.com/etesync/etesync-dav/actions
I still haven't managed to fix that.

**Comment by autobakterie** [comment]
Please also note that build artifacts (e.g., linked for [Version 0.33.4](https://github.com/etesync/etesync-dav/releases/tag/v0.33.4)) are only downloadable for users who are logged in. Artifact binaries only appear as a non-interactive list to those not logged in, and there isn't even any hint that logging in should help (not that it seems like a good idea to require users to have a GitHub account in the first place).

**Comment by tasn** [comment]
Grr, that's annoying. I added a note for now, but I'll think of a way to fix it.
