### ISSUE TITLE
etesync-dav.exe 33.4 not starting on Windows

### ISSUE THREAD

**Issue by NJCLous** [etesync/etesync-dav#335]
Hi Tom,

I downloaded version 33.4 of etesync-dav.exe for Windows and "installed" it as I did for previous versions by placing it in the Start-up folder (in Windows, executables in that folder are run at start-up). 

After restarting my computer, the etesync-dav service was not running - I checked via the Task Manager. I tried to start the service manually by double-clicking etesync-dav.exe but that didn't work either.

My firewall is set to always allow etesync-dav.exe and if I revert back version 33.1 everything works as normal.

Could you please help me out?

Thanks and best wishes,

Niels

**Comment by tasn** [comment]
Fixed.

**Comment by NJCLous** [comment]
Thanks Tom!
