### ISSUE TITLE
Syncing issue with Thunderbird (TbSync)

### ISSUE THREAD

**Issue by dmitry-112** [etesync/etesync-dav#35]
I started testing etesync with TbSync in Thunderbird earlier today and ran into a strange syncing issue that appears to be related to radicale. The initial sync after adding the account works fine for both contacts and calendar. Every sync attempt after that fails with the error listed below.

[7fafdf19e700] WARNING: Client provided invalid sync token 'http://radicale.org/ns/sync/9f53b65ef83f847b27e8a5708a587e515574b6632650ada8ff37f6b4d189208b': Sync token are not supported
[7fafdf19e700] WARNING: Client provided invalid sync token 'http://radicale.org/ns/sync/83f4f82e13304db0781c4e77886731bde5cbcc194e99e17cdfc430f1b691024b': Sync token are not supported

Installed packages:
etesync==0.5.6
etesync-dav==0.1.7
Radicale==2.1.11
radicale-storage-etesync==0.1.7

Please let me know if you need anything else. Thanks.

**Comment by dmitry-112** [comment]
I am also getting this error without TbSync, just Thunderbird with the Lightning add-on. Thunderbird version is 60.3.2, Lightning version is 6.2.3.2.

**Comment by dosqe** [comment]
i have the same error with the same configuration on windows using python. but everything is working as expected.

**Comment by dmitry-112** [comment]
TbSync syncing still fails with a 409 error. With just Thunderbird and Lightning, there appears to be a failed sync or a significant delay when I see that error, but after a few syncing attempts it eventually syncs fine.

**Comment by tasn** [comment]
Radicale doesn't currently support sync tokens. This is a known thing. It shouldn't affect sync though, it works here just fine with Thunderbird (haven't tried TbSync though).

**Comment by tasn** [comment]
Does this mean it now works?

**Comment by dmitry-112** [comment]
TBSync still does not work consistently.  Cardbook and lightning work well enough to be usable, so I will just use that combination.

Thanks.

**Comment by tasn** [comment]
Interesting. I honestly don't know, but it's most likely either an issue with TbSync or Radicale. EteSync is just a storage backend. :)
