### ISSUE TITLE
Native Windows build

### ISSUE THREAD

**Issue by dere** [etesync/etesync-dav#46]
Would be nice if there was a native Windows build (perhaps via PyInstaller), for the average joe who does not want to (or is scared to) install Python or Docker and follow the instructions.

**Comment by tasn** [comment]
Yeah, it's very much wanted. Not just for Windows to be honest, but also for Mac, and heck, maybe even Linux. Do you have any experience with pyinstaller? Just running it on this project didn't work unfortunately. It didn't pull Radicale correctly. I'm dying to have this, and help will be greatly appreciated!

**Comment by dere** [comment]
I've never used PyInstaller, but I ran into the same issue you're talking about. While I don't believe this issue is impossible to overcome, there is another alternative: pynsist achieves the same goal (allows you to run the application without installing Python or the pip dependencies)

**Comment by tasn** [comment]
Have you tried pynsist? If it works, I'm happy to give it a go.
Pyinstaller: I'm sure I can get it to work, just didn't have the time just yet.

**Comment by tasn** [comment]
Hm... Pyintsaller is proving problematic. I wonder if going with an appimage or something like that for Linux, py2app for Mac and Pynsist for Windows is the easiest option.

**Comment by dere** [comment]
I think it is most important to get Windows working. For Linux for example it may be preferable to make a .deb etc. I do not have a Mac, so I can't contribute anything to that case unfortunately.

So, only considering Windows for now, and since Python 3 support is a must, we are left with only a few options:

* PyInstaller, which isn't working correctly at the moment, but I did not spend much time on it
* py2exe, which PyInstaller is built upon if I understand correctly
* cx_Freeze, which unlike the above two, does not support one-file mode (which shouldn't be a huge concern to us, as long as it works)

I will play around with these for a little and see if I can uncover anything useful.

**Comment by tasn** [comment]
That would be awesome, thanks! I reached out to the pyinstaller devs on IRC but haven't heard back yet. Will follow up again.

**Comment by tasn** [comment]
After a lot of work and even more pain, I finally got pyinstaller to work (or so it seems)!
I'm fixing a few more things, but it looks like I may be able to get some binaries out very soon!

**Comment by tasn** [comment]
It works on both Linux and Mac. I'm trying to get my hands around a Windows box to test it there, would be great if you could do it. You just need to get to a working etesync-dav (probably in a venv) and then 
```
pip install PyInstaller
cd pyinstaller
# Run the command from within the .sh file in that directory
pyinstall ...
```

You'll then have an exe in the dist directory which will hopefully work. :)

Bear in mind, that even with all of this, it's still a command line application, though I hope to add a GUI at some point. Shouldn't be too hard.

**Comment by dere** [comment]
I can spin up a Windows VM, but I have never set up a development Python environment on Windows so it will take me a bit of time to make sure everything is correct (the PATH and dependencies and whatnot).

Setting up Travis CI or something similar may be important as well. Since PyInstaller bundles all dependencies, we will need to rebuild any time there is a security patch to cryptography, openssl, or any other important package.

A command-line application should be fine for now, because it can run in the background as a service upon startup.

**Comment by tasn** [comment]
No need, it works!

I managed to build a working exe, Linux executable and a Mac executable. :)

Thanks a lot for all of your help with this. I'll sign + upload the executables soon, and update the README accordingly. Yay, thanks a lot for the nudge!

**Comment by dere** [comment]
What Windows OS did you test it on?

**Comment by tasn** [comment]
Windows 10 64bit Pro.
You can try the exe here: https://uploadfiles.io/2drlk
If not, wait until it's uploaded, maybe tomorrow actually, as I have to go in a moment.

**Comment by dere** [comment]
It runs for me as well on Windows 10 64bit Education Edition. Unfortunately I couldn't test it in detail though because I don't have a config. When etesync-manage gets uploaded to the website, I can test them both more thoroughly.

Unfortunately, it gets blocked by SmartScreen which I expected since it's a very common problem these Python bundlers. Also unfortunately, I don't know if there is a way for a developer to get their applications signed by Microsoft to make this not happen, so it will need to be mentioned on the website in the install directions.

Thirdly, while it worked for me and you so far, this isn't expected to work for all Windows users because of Visual C++ runtime dependencies I just happen to have installed (and probably you as well). [Here](https://pyinstaller.readthedocs.io/en/stable/usage.html#windows) is more information. It suggests two solutions: either you distribute the DLLs with your application (which may or may not have licensing conflicts, licensing is out of my depth) or have the user install it during the install process (a lot of Windows software does this). Either way you will need some sort of installer, like the free NSIS.

Speaking of running it on startup: there is an easy way anyone can do it, but that will make the command prompt window open any time it is running. A better way is for it to run as a background service. There is no easy way for a user to configure this. However, NSIS has a well-liked plugin called Simple Service Plugin that handles this for you.

**Comment by tasn** [comment]
You don't need a config. This command includes both the manage and the regular (they are now merged). Just run `etesync-dav manage add ....` like you would otherwise.

What's SmartScreen? An anti-malware thing?

Visual C++ runtime: it's now part of Windows in any up to date Windows since Windows Vista, so I think it's no longer a concern.

NSIS: are you familiar with it? Would be great if you could help with getting this to work.

Thanks!

**Comment by dere** [comment]
Ah, I didn't know that they are now merged. I created a config and started up the server and it seems to be working great. Good work!

SmartScreen: yes, it's an anti-malware thing in Windows 10, but instead of scanning the file (which is Windows Defender) it hashes the file and phones home to Microsoft to see if it's a commonly-executed file. This means that, while it's a scary warning now, as the executable becomes more popular, in the future Microsoft might stop triggering the warning.

Visual C++ runtime: the link I included above (which was the PyInstaller documentation) says the runtime is included in Windows 10, not in all Windows versions since Vista. So it is still a concern according to the Pyinstaller developers

NSIS: I have actually never used it before, and while it's popular I don't know if it's the best thing. I only  mentioned it as an example of a solution for the visual c++ runtime problem and to install the exe as a service. I could probably get it working but it seems you're working faster than my schedule is allowing me to, so maybe you'll get it done before me :)

**Comment by tasn** [comment]
I merged them as part of this change to make it easier to just distribute a single binary.

C++ runtime, from your link:

>  For Windows Vista through Windows 8.1 there are Windows Update packages, which may or may not be installed in the target-system. 

It looks like an up to date system will have it. Sure, not a sure thing, but much better than before.

P.S, we now include signed binaries in the release page, and updated the README accordingly. \o/


I think we can close this task, thoughts?

**Comment by dere** [comment]
I interpreted that to mean the packages were distributed via Windows Update, which is simply just the way Microsoft distributes software (not necessarily updates, for example, Language Packs are installed this way, but you have to manually search for it and enable it). However, after more research it turns out you're correct anyway:

> The Visual C++ runtime was refactored into Universal CRT, which is part of Windows 10. For Vista and Windows 7 machines, the Universal CRT is a Recommended update, so by default, most machines install it as part of the regular update process, unless the machine does not automatically install updates or only installs Required updates.

I also realize that, while possible, it would be really rare for someone who uses a Windows machine to not have these packages installed, since so much consumer software installs it whether or not you already have it. Personally, my Windows machine has 12 different versions installed, even though it should be built into Windows on this version.

Yes, I think we can close this task. Getting the executable installed as a Windows service is a nice UX feature, but it can wait for a larger milestone with the GUI etc.

**Comment by tasn** [comment]
I agree, will close it now, thanks.

Though I guess it's better to have a ticket for that one as well, as it should be trivial. Will have a think.
