### ISSUE TITLE
AppImage instead of misc Linux executable

### ISSUE THREAD

**Issue by KyleFN** [etesync/etesync-dav#48]
I'm not sure what filetype the Linux executable is but it doesn't run by double-clicking the app on a KDE desktop. Instead package it as an [AppImage](https://appimage.org/) since that's a single-file executable than runs on any Linux distro. 

When I try to run it via `./linux-etesync-dav` I get this error message:
`[7579] Error loading Python lib '/tmp/_MEIo4ugqf/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIo4ugqf/libpython3.7m.so.1.0)`

I'm not sure if this is referring to a missing dependency, but if so it's strange because I have the previous Python-based etesync-dav working correctly. This would also be something solved by using AppImage since you can package dependencies together in the executable.

**Comment by tasn** [comment]
It seems to be a limitation of PyInstaller: https://github.com/pyinstaller/pyinstaller/wiki/FAQ#gnulinux

I'd need to install an old Linux distro to build the binary with to avoid this issue. Quite annoying, but I'll do it soon...

I looked into AppImage before, but it's yet another configuration to maintain. We already use PyInstaller for Mac and Windows, so we may as well use it for Linux too...

Thanks for reporting!

**Comment by tasn** [comment]
Fixed, thanks again for reporting!
