### ISSUE TITLE
Help message(s) do(es) not yet reflect the fact of a single binary version

### ISSUE THREAD

**Issue by porg** [etesync/etesync-dav#55]
**Foreword**: Ironically I delayed EteSync adaption as I wanted to install it with Docker, which I then finally had, only to find out, that there's now a single binary installation. Great news!

The help message(s) do(es) not yet reflect that etesync-dav is now a single binary, i.e.:

```
$ etesync-dav --version
Configuration not found. Please run etesync-dav-manage first
```

Should be `Please first run "etesync-dav manage" (without the quotes)`.

Maybe there are other messages too which yet don't reflect that change.

**Comment by tasn** [comment]
Oops, thanks, fixed! I'll release a new version once I fix the rest of the issues.

**Comment by porg** [comment]
Currently I fail to setup etesync on my macOS 10.14.4 due to #41

Could you look into it? And then maybe with the new executable (or Homebrew installation which would be even more convenient) I hope to eventually succeed getting etesync up and running.

**Comment by tasn** [comment]
Could you please open a task about Homebrew?

I'l take a look at the rest as soon as I can.

**Comment by porg** [comment]
Created feature request #57 

Thanks for offering to look into my setup problems due to #41

**Comment by tasn** [comment]
Thanks.
