### ISSUE TITLE
Ensure and/or document how etesync-dav-certgen works in the single executable context

### ISSUE THREAD

**Issue by porg** [etesync/etesync-dav#56]
- Automatic SSL setup via the command `etesync-dav-certgen --trust-cert` is not working in the context of the single executable (like other commands too, see #55)
- I tried to rephrase as `etesync-dav certgen --trust-cert` or `etesync-dav --certgen` or `etesync-dav --trust-cert` or `etesync-dav --certgen --trust-cert` but none of this worked.

**Comment by tasn** [comment]
Yes, it's not yet supported unfortunately. I still need to figure out the correct way of attacking this. I may just bundle it inside too, maybe add it to manage. It's on the list.

In the meanwhile you can use the manual instructions or just download the etesync-dav-certgen binary separately (it should be standalone).

**Comment by porg** [comment]
The usability goal is to install etesync as easily as possible,
1) Totally easy for a mass audience: Appstore download or Installer.
2) Quite easy and convenient, but already a smaller audience: Via a package manager, such as Homebrew #57
3) Expert/skeptic: Source download, source inspection, building yourself.
4) Single executable for download and placement in the usual directory is somehow a middleground of 1-3.

I cannot estimate the effort, but if development resource are scarce then they may be better spent on #57 than polishing that single executable to reflect everything which was split among different executables before, especially when there are workarounds (such as signing certificate yourself from a HowTo instruction).

**Comment by tasn** [comment]
I agree with the goal. That's why it was done in the first place. We are working on it. Having the single executable was a step in that direction. While many people use Homebrew, I don't think the vast majority does, so I don't think #57 is a solution, just a nice addition.

**Comment by porg** [comment]
https://github.com/etesync/etesync-dav/releases/tag/v0.5.0

The precompiled version only offers  "<YourOS>-etesync-dav" but not "<YourOS>-etesync-dav-certgen". So for now only manual certificate creation is possible.

**Comment by tasn** [comment]
Yeah, I'm aware of that. I want to merge it into the same executable.

**Comment by tasn** [comment]
Now there's a UI, but the UI doesn't deal with certgen. On the plus side, we can quite easily add a banner (warning) and a button to start the certgen process.
