### ISSUE TITLE
How to use with self hosted server

### ISSUE THREAD

**Issue by x11x** [etesync/etesync-dav#6]
Hi,
Thanks for making this great open source software.
Just wanted to point out (as its not in the Readme) that you need to set the `ETESYNC_URL` environment variable to your server if you are self-hosting or running a local instance for testing.
Other config variables can be found in config.py
Maybe this info could be added to the readme?

**Comment by tasn** [comment]
Same as my comment to #7 (copy-paste below).

You already did 90% of the work to solve this ticket, would you be interested in opening a pull request so you'll be properly attributed in the commit log?
If you don't have the time, or don't care, let me know, and I'll do it myself.

Thanks!

**Comment by tasn** [comment]
Fixed by #9.
