### ISSUE TITLE
Implement sync-token support

### ISSUE THREAD

**Issue by plague-doctor** [etesync/etesync-dav#62]
Please implement sync-token support.
Using providers like TbSync throw errors:
```
URL:
https://etesync-dav.<my-domain>/<my-account>/c7395195582<...>72ceea629da9640/ (REPORT)

Request:
<d:sync-collection xmlns:d="DAV:"><d:sync-token>http://radicale.org/ns/sync/2e138cc284a8<...>202b24016bd</d:sync-token><d:sync-level>1</d:sync-level><d:prop><d:getetag/></d:prop></d:sync-collection>

Response:
<?xml version='1.0' encoding='utf-8'?>
<error xmlns="DAV:">
<valid-sync-token />
</error>
```

**Comment by tasn** [comment]
As discussed externally, TbSync shouldn't fail over this, as not implementing sync token is technically within spec for all I know. With that being said, it's something I'd like to have regardless and sholudn't be too hard to implement.

Thanks for opening this ticket.

**Comment by tasn** [comment]
As suspected, it was indeed an issue with TbSync and has now been fixed in the TbSync beta channel, thanks a lot @jobisoft!

I'm therefore closing this one (sync-token support itself is a low priority item that will hopefully be done in the future and is already on the wishlist, but is not an issue).

**Comment by tasn** [comment]
And it's now been released! Just make sure your DAV provider is up to date, and everything should work!

**Comment by devurandom** [comment]
> And it's now been released! Just make sure your DAV provider is up to date, and everything should work!

I see the following in my logs from `etesync-dav`:
```
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
```

Was a development / debug build released by accident or is this expected?
```
# etesync-dav --version
EteSync DAV version:  0.8.1
Radicale version:  2.1.11
```

**Comment by tasn** [comment]
Nah, it's fine. It's for the management interface. I need to figure out how to silence this because what they (flask) mean when they say production is very different to a standalone app that's only listening on localhost and using it for a configuration UI. :)

**Comment by jack-movember** [comment]
Yay! Thank you @tasn
:+1:
