### ISSUE TITLE
Finding CalDAV/CardDAV collection URLs for clients that can't do this automatically

### ISSUE THREAD

**Issue by x11x** [etesync/etesync-dav#7]
Hi, just another piece of info for the docs:
I found an easy way to find the collection URLs in the case that the CalDAV client can't find them from the main URLs (e.g. Thunderbird + Lightning). This is easier than using the mentioned `example.py` script or looking in the debug info of the Android app.
Radicale serves a simple Web UI at http://localhost:37358/. You just need to log in with the username and password generated by the `etesync-dav-manage` script.
Then you can just right click on the collection URL links and copy URL and paste them into your client.

**Comment by tasn** [comment]
Thanks for the tip!
You already did 90% of the work to solve this ticket, would you be interested in opening a pull request so you'll be properly attributed in the commit log?
If you don't have the time, or don't care, let me know, and I'll do it myself.

Thanks!

**Comment by tasn** [comment]
Fixed by #9.

**Comment by Dremet** [comment]
This should totally be included in the README. Would have saved me 30 minutes.

**Comment by tasn** [comment]
I agree, sorry about that!

Can you please open a PR with the suggested changes? Would love to add it! The reason why it wasn't there originally is because this project started before Radicale had this web UI...

**Comment by Dremet** [comment]
Just saw that it is actually included, but not where I expected it. Hmm, so probably I would just suggest to structure the README better. I am not very into the technical specifications to be honest. I do not think that I should edit this. I might think about it later on though.

**Comment by tasn** [comment]
Where would you have expected it? I just realised it is there, in configuration and running.
