### ISSUE TITLE
etesync-dav --version reports wrong version

### ISSUE THREAD

**Issue by sonea-pm8** [etesync/etesync-dav#72]
OS: Arch Linux
etesync-dav version: 0.50.0-1 from AUR

```
$ etesync-dav --version
2.1.11
```
should be 0.50.0, shouldn't it? Is this the radicale version etesync-dav is based on?

**Comment by tasn** [comment]
Yeah, it's the radicale version. At the moment etesync-dav just forwards all of the flags to radiacle. It should probably swallow some of them. This is one of them I guess. :)
