### ISSUE TITLE
syncing events with outook-generated UIDs fails

### ISSUE THREAD

**Issue by sonea-pm8** [etesync/etesync-dav#73]
OS: Arch Linux
etesync-dav version: 0.50.0-1 from AUR

I exported some events as free/busy from outlook at work, which resulted in events with UIDs like `ScCeRgxA00KpJgJqK+igew==` or `OsWBOZF/B0acL6anHhDAiw==`. Importing them in android worked fine, so did uploading them to the server. 

But etesync-dav has problems with the events where the UIDs contain "/". The calendar from the webinterface shows that they were downloaded fine. 

But showing them in thunderbird fails, `etesync-dav` says
`
Jun 26 18:30:25 *** etesync-dav[21203]: [***] WARNING: Skipping invalid path '/username/ebbfad7c6aa10081ac18cc5e93ed21bb670cbcaa46cec17816be7fa592765605/222Oy7wK2ECKeM3iv/zI/w==.ics' in REPORT request on '/username/ebbfad7c6aa10081ac18cc5e93ed21bb670cbcaa46cec17816be7fa592765605/': '222Oy7wK2ECKeM3iv/zI/w==.ics' is not a component in collection 'username/ebbfad7c6aa10081ac18cc5e93ed21bb670cbcaa46cec17816be7fa592765605'
`

**Comment by sonea-pm8** [comment]
https://github.com/Kozea/Radicale/issues/262 seems related

**Comment by tasn** [comment]
Ah, interesting. I had no idea that was even legal. Easiest workaround for you would be to delete the relevant events, and then potentially upload them again with new UIDs that don't contain slashes (you can manually edit the file before importing).

As for the issue itself: I guess we need to urlencode the uid before using it in the path (duh!). I'm surprised Radicale doesn't do it automatically though.

**Comment by tasn** [comment]
I'm working on a fix, and I think I'll be able to get something working.

Though there's an underlying issue with Radicale which I've reported here: https://github.com/Kozea/Radicale/issues/962

**Comment by sonea-pm8** [comment]
Thanks for being so quick :). I figured that would be the workaround. Editing the uids of the of the events already in etesync is not a good idea, is it?

As to legal characters: The ical-RFC (5545) defines the UID as a TEXT field, which in turn is defined in [section 3.3.11](https://tools.ietf.org/html/rfc5545#section-3.3.11) of the RFC. It allows `Any character except CONTROLs not needed by the current character set, DQUOTE, ";", ":", "\", ","`. Those last 5 must be escaped with "\\". 
So I think urlencoding the UID is a good idea :)
