### ISSUE TITLE
A server error after upgrade to 0.8.1

### ISSUE THREAD

**Issue by plague-doctor** [etesync/etesync-dav#75]
Hmmm... Everything was working till today's upgrade to latest release. Now when I go to:
https://etesync-dav.xxxx.net/myuser/e95a9xxxxxxxxxxxxxxxxxxxxx58b313
I get the request to authenticate, and as soon as I do it, the server throws at me:
```
A server error occurred.  Please contact the administrator.
```
Obviously the `TbSync` on my Thunderbird keeps complaining:
```
URL:
https://etesync-dav.xxxx.net/myuser (PROPFIND)
Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>
Response:
A server error occurred.  Please contact the administrator.
```
Any suggestions on how to tackle this issue?

**Comment by tasn** [comment]
Which version did you upgrade from? Can you run etesync-dav with -D

Though I suspect I know what it may be. EteSync-DAV always required you run with `ETESYNC_URL` set when using a non-standard EteSync server. Could you please make sure that's set correct to https://etesync.xxxx.net or wherever your server is? EteSync-DAV no longer respects the radicale configuration file.

**Comment by plague-doctor** [comment]
And everything works like a charm again. TYSM @tasn

**Comment by tasn** [comment]
Sorry about this. :)
