### ISSUE TITLE
Providing invalid encryption key error message

### ISSUE THREAD

**Issue by zakkak** [etesync/etesync-dav#78]
When adding a new account to the web UI if a wrong encryption key is provided the user is not made aware of the mistake and the account creation completes normally. Later when trying to connect to the etesync-dav server authentication fails with not much details on the reason. If ran in DEBUG mode, etesync-dav will print an error which is not very clear though. The said error message is "HMAC mismatch". 

I believe the best would be to let the user know that he inserted an incorrect encryption key when creating the new account in the web UI.
A more descriptive message in the terminal when running in DEBUG mode would also improve things :)

Related to #77

**Comment by tasn** [comment]
Thanks! Will try to get to it in the near future!
