### ISSUE TITLE
SSL not working on MacOS [SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by zakkak** [etesync/etesync-dav#81]
`etesync-dav -D` gives the following log. Any clues?

```
[7000109dc000] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
Traceback (most recent call last):
  File "site-packages/radicale/__init__.py", line 193, in process_request_thread
  File "ssl.py", line 1117, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "site-packages/radicale/__init__.py", line 197, in process_request_thread
RuntimeError: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)
```

**Comment by zakkak** [comment]
This happens when I try to access a calendar or the contacts through the web interface.

**Comment by tasn** [comment]
I've also had it a few times. I think it's because it's for some reason trying to use HTTP to access an HTTPS resource. Could that be the case?

**Comment by zakkak** [comment]
Yes, that's correct.
Not sure whether this is worth fixing or not :/
I would never try to access them through the webUI if not debugging.

**Comment by tasn** [comment]
There's nothing to fix, just access the web ui with https://localhost:37358 instead of http://localhost:37358 or am I misunderstanding the situation?

**Comment by zakkak** [comment]
By a fix I mean that Ideally I would expect the webUI to automatically redirect me to https if SSL is required and the script to print `Running on https://127.0.0.1:37359/` instead of `Running on http://127.0.0.1:37359/` or similar.

**Comment by tasn** [comment]
This is a different one. This one is running on HTTP (it's the management console), the dav service is the one using SSL (needed because of the bug in the Mojave).

As for your suggested change, I don't know if it's possible, but it's the case with every since I'm aware of. For example:
```
$ curl https://github.com:80
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

It's just more annoying for us because we pin the port to 37358 which is used for either http or https.

In summary, I don't think there's anything that can be done. Should this be closed?

**Comment by zakkak** [comment]
> Should this be closed?

As I said I don't think this is worth fixing. So yes let's close this.
