### ISSUE TITLE
Will not synchronize when I add new calendar.

### ISSUE THREAD

**Issue by HybridGlucose** [etesync/etesync-dav#84]
I try to delete old `etesync_data.db` and restart etesync-dav will get new file.
So I think this step is no problem, but there is empty in this file (I guess), it only have 76K size.
And I run `radicale` directly will get this error : 
```
[etesync@mail etesync-dav]$ radicale -D -C radicale.conf 
[b6fe9010] INFO: Starting Radicale
[b6fe9010] INFO: Authentication type is 'htpasswd'
[b6fe9010] ERROR: An exception occurred during server startup: Failed to load storage module 'radicale_storage_etesync': No module named 'radicale_storage_etesync'
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale/storage.py", line 107, in load
    collection_class = import_module(storage_type).Collection
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'radicale_storage_etesync'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/radicale/__main__.py", line 138, in run
    serve(configuration, logger)
  File "/usr/lib/python3.7/site-packages/radicale/__main__.py", line 229, in serve
    application = Application(configuration, logger)
  File "/usr/lib/python3.7/site-packages/radicale/__init__.py", line 252, in __init__
    self.Collection = storage.load(configuration, logger)
  File "/usr/lib/python3.7/site-packages/radicale/storage.py", line 110, in load
    (storage_type, e)) from e
RuntimeError: Failed to load storage module 'radicale_storage_etesync': No module named 'radicale_storage_etesync'
```
But run `etesync-dav` have no error like this:
```
[etesync@mail etesync-dav]$ etesync-dav -D
 * Serving Flask app "etesync_dav.webui" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[b6f3d010] INFO: Starting Radicale
[b6f3d010] INFO: Authentication type is 'htpasswd'
[b6f3d010] INFO: Storage type is 'etesync_dav.radicale.storage'
[b6f3d010] INFO: Rights type is 'etesync_dav.radicale.rights'
[b6f3d010] INFO: Web type is 'etesync_dav.radicale.web'
[b6f3d010] INFO: Listening to 'localhost' on port 37358
[b6f3d010] INFO: Radicale server ready
 * Running on http://127.0.0.1:37359/ (Press CTRL+C to quit)
```

I think those are something need to find problem if need other info please fell free to ask me.
After something long,the problem is : db file will not get update when I add or delete some `task` or `calendar`, but in old file (that old version etesync-dav generate) works fine add or delete `event`.

**Comment by tasn** [comment]
Don't run with -C, newer versions of etesync-dav don't need the configuration file (in fact, you should delete it).

After creating the new file, did you log into etesync-dav from any DAV client? I'm not sure I follow what you're doing, though the easiest solution to make sure you're not doing anything wrong is to remove the directory (`~/.config/etesync-dav`) and follow the instructions from scratch.

**Comment by HybridGlucose** [comment]
I delete the folder and re-generate a new one by program.
Add a new account, and get a DAV password, click username still get a empty list.

**Comment by tasn** [comment]
Could you please be more specific about the steps you took?
If I understand you correctly, you:
1. `rm -r ~./config-etesync-dav`
2. `etesync-dav manage add EMAIL`
3. run `etesync-dav`
4. Add the DAV account to your calendar application

And you still don't see anything? Does etesync-dav print out anything important looking? What about when running with -D? What calendar application do you use? Thunderbird + TbSync?

**Comment by HybridGlucose** [comment]
I delete config like you do and run `etesync-dav -D`.
Open the EteSync DAV Management web page, sing in to etesync server (just like you do but via web do).
Username, password and encryption password.
```
127.0.0.1 - - [19/Aug/2019 02:40:22] "GET /add/ HTTP/1.0" 200 -
Fetching auth token
Deriving password
Saving config
127.0.0.1 - - [19/Aug/2019 02:40:32] "POST /add/ HTTP/1.0" 302 -
```
And go back to login form, login, click my username and the problem happens.
I can't see anything I own at EteSync DAV Management page,there are just a page title.
![screenshot](https://i.imgur.com/GR0bS3O.jpg)

If I can't login server I will not receiving key ,right?
So I think server side are find.

**Comment by tasn** [comment]
Are you able to jump onto IRC at any point for some live debugging? This is indeed weird and shouldn't happen.

**Comment by HybridGlucose** [comment]
> Are you able to jump onto IRC at any point for some live debugging? This is indeed weird and shouldn't happen.
Sorry for replay so late, which IRC server and channel should I go?
And maybe we can decide a time both of us are free to solve this problem.

**Comment by tasn** [comment]
#etesync on freenode.
More details: https://www.etesync.com/about/#contact

Yeah, happily. How about in two hours? So 4pm UTC? Just ping me there (tasn).

**Comment by HybridGlucose** [comment]
> #etesync on freenode.
> More details: https://www.etesync.com/about/#contact
> 
> Yeah, happily. How about in two hours? So 4pm UTC? Just ping me there (tasn).

Got it.
