### ISSUE TITLE
Certificate Error for Localhost using Firefox (macOS Mojave)

### ISSUE THREAD

**Issue by lasscap** [etesync/etesync-dav#85]
After setting up etesync-dav to SSL Firefox prompts me with the error that my certificate is not trustet. The error code is: MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT

I marked the certificate in Keychain Access as "Always Trust" but Firefox does not accept that.

What would be the real risk of proceding?
<img width="1440" alt="certificate-error-etesync-dav" src="https://user-images.githubusercontent.com/47210775/63166800-bb4ea480-c02f-11e9-96c7-45394ecc53af.png">

This issue might me a duplicate with #41

**Comment by tasn** [comment]
Firefox on Mac doesn't rely on the system's keychain if memory serves, so you'd need to add an exception here separately ("Accept the risk and continue"). So unfortunately it's not something we are able to do anything about and it's OK to just go on and accept it.

**Comment by lasscap** [comment]
Okay, thanks!
