### ISSUE TITLE
OS X Mojave, etesync-dav process not responding

### ISSUE THREAD

**Issue by embamba** [etesync/etesync-dav#87]
On OS X Mojave 10.14.6, I've noticed in the Activities Monitor, one of the two etesync-dav processes displays as "Not Responding" with its line in red typeface. It's always the item with the app icon next to the process name, never the other process. Sometimes, it takes on this status within seconds after it launches. Other times, it takes longer. But it seems that after some period of time, it always gets there. 

That said, I see no evidence that the process is actually hanging. Syncing works. Still, once the Activity Monitor identifies the process as not responding, it stays that way, even if it's working fine. Other processes, on occasion, go to not responding, then, after a few seconds or minutes, return to normal status.

In a browser window, https://localhost:37358 sometimes reroutes to localhost:37359. Other times, it fails, not necessarily when the process is not responding.

Syncing is successful in Thunderbird's TbSync addon. But I sometimes get a non fatal error (409) in the address book that I'm syncing. The error part of the log reads:

<error xmlns="DAV:">
<valid-sync-token />
</error>

**Comment by tasn** [comment]
Thanks for reporting! Your message is cut after "the error part of the log reads:", could you please add the missing part?
From your description I believe we probably need to send a sort of a "ping" to activity monitor to let it know we are responding which we are not doing at the moment.
I'm a bit concerned about the reroute from 37358 to 37359 not always working, but it could just be that when you are testing it's a bit overloaded. Because etesync-dav is only intended to serve one user, it's number of worker threads is not very high.

**Comment by embamba** [comment]
Thanks for noticing the missing log data.

<error xmlns="DAV:">
<valid-sync-token />
</error>

**Comment by zakkak** [comment]
@embamba you can wrap the code in backquotes to make it appear properly.

e.g.
````
```
<error xmlns="DAV:">
<valid-sync-token />
</error>
```
````

will appear as 
```
<error xmlns="DAV:">
<valid-sync-token />
</error>
```

**Comment by tasn** [comment]
Thanks @zakkak for weighing in!

@embamba: as we said, it works, right? It's just the activity monitor that shows it, right?

**Comment by zakkak** [comment]
In my case when it is not responding Calendar fails to sync. I never tried leaving it long enough to see if it ever revives, I usually kill the process and restart.

**Comment by tasn** [comment]
Does it actually happen to you often? I wonder if the Mac actively stops it because we don't do whatever they want us to do regarding "pings".

**Comment by zakkak** [comment]
I think once every couple of days. I will try to monitor it from now on.

**Comment by zakkak** [comment]
Right now I see it not responding but my contacts and the calendar are syncing fine

<img width="668" alt="image" src="https://user-images.githubusercontent.com/1435395/63811246-9f040f00-c92f-11e9-8ca8-c0710776c087.png">

**Comment by tasn** [comment]
Thanks for the information!

@embamba: yeah, Contacts should now work! Let me know (in another ticket, possibly #70 if it's no longer the case).

**Comment by lasscap** [comment]
I had the same problem but everything worked fine with 0.9.1. Now I have updated to 0.11.0 and Activity Monitor shows me two entries/programs running for etesync. And one sometimes has ridiculously high CPU usage.
<img width="912" alt="Screenshot 2019-09-03 at 15 12 13" src="https://user-images.githubusercontent.com/47210775/64176926-aca12380-ce5e-11e9-84b1-d523b7477105.png">

**Comment by tasn** [comment]
The CPU usage is probably because it's performing a large sync. Could you maybe run it with -D to see if there are any obvious error messages? Is the CPU usage momentary? If so, I wouldn't worry about it.

**Comment by lasscap** [comment]
Yes, you are correct :)

**Comment by tasn** [comment]
About which part? It's just a momentary large sync?
This is going to significantly improve in the future btw, but it should already be quite good, momentary and rare as it is. :)

**Comment by lasscap** [comment]
Yeah, that it is a momentary large sync. But I am still surprised because it is quite a large consumption of recourses.

**Comment by tasn** [comment]
It needs to decrypt all of your data which could be quite a bit, especially since at the moment it's done in Python if memory serves, rather than a faster implementation.
