### ISSUE TITLE
No way to quit the etesync-dav process on OS X?

### ISSUE THREAD

**Issue by embamba** [etesync/etesync-dav#88]
Looking through command line help for etesync-dav on Mac, I don't see any -q or whatever argument to quit the process(es). I've only quit because I'd seen the apparently false alarm "Not Responding" status in the Activity Monitor, so it was a way to restart the process to clear that out. I've quit through Activity Monitor. But I see no way of doing this directly through etesync-dav. This is not a high priority item, at least for me, but it would be helpful to have.

**Comment by tasn** [comment]
Nice catch! There's no way at the moment. Oops. :)

I just never assumed anyone would quit it! I should just add a "stop daemon" button from the web UI.

Thanks!
