### ISSUE TITLE
Add information about setting it up with Windows 10's contacts/calendar

### ISSUE THREAD

**Issue by tasn** [etesync/etesync-dav#90]
I'm opening this following a report from a user where he wasn't able to set this up.
We need to make sure it works as expected and then add instructions to the readme.

Apparently also, Windows 10 no longer has cal/carddav but you need to choose "iCloud" and then change the server's url. More info: https://github.com/nextcloud/documentation/blob/master/user_manual/pim/sync_windows10.rst

**Comment by sawft99** [comment]
Addressed in https://github.com/etesync/etesync-dav/wiki/Windows-10-instructions ?

**Comment by tasn** [comment]
I believe so, thanks!
