### ISSUE TITLE
Authentication fails in Thunderbird

### ISSUE THREAD

**Issue by besendorf** [etesync/etesync-dav#91]
I am running skeleton with with docker on my server and installed etesync-dav on my laptop with the AUR package.
Then I set up etesync-dav using the web interface. This works and I can access http://localhost:37359/user/myuser
Also the everything works with the Android client and the web client.
However when I want to use Thunderbird it always fails with an authentication error.
With TbSync I used this options:
Accountname: myuser
CalDav server address: http://localhost:37358/myuser/
CardDav server address: http://localhost:37358/myuser/
User name: myuser
Password: myloginpassword

(I changed myuser and myloginpassword for this thread)

Error in TbSync:
```
URL:
http://localhost:37358/myuser (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
Access to the requested resource forbidden.
```
stdout of etesync-dav:
```
$ etesync-dav
 * Serving Flask app "etesync_dav.webui" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:37359/ (Press CTRL+C to quit)
127.0.0.1 - - [17/Sep/2019 17:00:02] "GET / HTTP/1.1" 302 -
127.0.0.1 - - [17/Sep/2019 17:00:02] "GET /login/ HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2019 17:00:07] "POST /login/ HTTP/1.1" 302 -
127.0.0.1 - - [17/Sep/2019 17:00:08] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/Sep/2019 17:00:13] "GET /user/myuser HTTP/1.1" 200 -
```

I also tried using Lightning (the standard Thunderbird CalDAV addon) but that also gave me an Authentication error.
Also clicking on the links in the browser at http://localhost:37359/user/myuser promts for a password an then fails.

Im quite sure the passwords are correct because before I had a typo and etesync-dav failed with HMAC mismatch

I think its quite confusing that the official server uses the e-mail as username by default but skeleton doesnt force you to do so. Could there maybe be a problem here?

**Comment by tasn** [comment]
You shouldn't be using your login password, but rather etesync-dav creates a new password for DAV clients.
Open http://localhost:37359 and there, next to the username you'll have a button to "copy password" to get a password you can use for DAV clients.

**Comment by tasn** [comment]
Did it solve it?

**Comment by besendorf** [comment]
Oh yes it did. Sry I forgot to awnser.Thank you very much

**Comment by tasn** [comment]
Great! I really need to fix this UI as you're not the only one who got confused there. Will open a ticket.
