### ISSUE TITLE
People get confused about the separate DAV password

### ISSUE THREAD

**Issue by tasn** [etesync/etesync-dav#92]
* Either change it to just use the service password (would need to run scrypt on it or something before).
* Or make the UI better.

Don't forget about the hosted DAV service when making these changes.

One recent example where a person got confused by it is in #91

**Comment by jeremiah-miller** [comment]
Another possible solution is just updating the README.md to include using the "Copy Password" button, for example with gnome calendar:
> Evolution / GNOME Calendar / GNOME Contacts
> GNOME Calendar and Contacts do not support adding WebDAV calendars and address books directly, but you can add them in Evolution and they will appear correctly in all the apps.
> 
> 1. Open Evolution and click File -> New -> Calendar (or address book, depending on what you're adding).
> 2.      Set type to CalDAV (CardDAV for address books) - Do not set "One The Web"
> 3.      Use http://localhost:37358/user@example.com/ as the server.
> 4.      Put your username (user@example.com) in the user field.
> 5.      If a username and password is requested, use your username (user@example.com) as the username, and get the password by clicking "Copy Password" next to your username in the list at http://localhost:37359/
> 6.      Click "Find Calendars" and choose your wanted calendar.
> 7.      Click OK

**Comment by tasn** [comment]
Fixed, thanks for the idea!

**Comment by jeremiah-miller** [comment]
My pleasure, thank you!
