### ISSUE TITLE
Event creation and editing via Thunderbird is very slow

### ISSUE THREAD

**Issue by Peter4487** [etesync/etesync-dav#93]
Creating a task takes as long as 10 seconds sometimes. I am happy to produce logs, but I don't know how to turn on logging in etesync-dav, nor do I know where to look for the logs.

**Comment by tasn** [comment]
To turn on logging you can run `etesync-dav -D`.

When you say creating a task takes as long as 10 seconds sometimes. Are you referring to the time it takes from when the task is saved on Thunderbird until it shows on the server, or is it blocking Thunderbird for that period?
Does it also happen with contacts/events?
What are you using on Thunderbird, just lightning, or are you using TbSync? If you're not using TbSync, could you please try that?

Thanks!

**Comment by Peter4487** [comment]
Hi tasn, thank you for the help

- I'm referring to the time it takes from when I ask Thunderbird to add a task until the task shows in Thunderbird--I think this is the "blocking period" you refer to

- It happens with events (I've changed the issue name, tasks was incorrect). Contacts seems snappy, and I don't use tasks

- On Thunderbird, I'm using Lightning + TbSync, per the Etesync instructions

Logs are attached. The pause is after "[alphanumeric] INFO: Successful login: 'email@domain.com'"

[logs_debug_1.txt](https://github.com/etesync/etesync-dav/files/3678377/logs_debug_1.txt)

**Comment by tasn** [comment]
I don't think you can use both Lighting and TbSync. Unless you mean lightning for the UI, but you configured the calendar only in TbSync, is that correct?
Have you tried asking the TbSync developers?

**Comment by Peter4487** [comment]
Yes, Lightning for the UI but TbSync for talking to the Cal-DAV server.
I have not tried asking the TbSync developers, but I will if you think that's the correct route.

Each of the pauses are of interest, I guess. The first one has the line [alphanumeric-2] INFO: PUT response status for '/email@domain.com/alphanumeric-code/another-alphanum-code.ics' in 7.234 seconds: 201 Created, which seems to report about 7 seconds

**Comment by tasn** [comment]
What happens if you create an event, wait until it's created, and then immediately create another one?
Is that one also slow?
How are you by any chance very far from our servers (Europe)?

I'm just trying to gather more information.

**Comment by Peter4487** [comment]
Yes of course, happy to provide the information.

Creating a first event took about 11s (11s until the event appeared on Lightning's calendar display with "New Event", ready to be edited). Subsequent events created in the few seconds after that 11s event took 2-3s to appear with "New Event".

I'm on the east coast of the US, NYC.

**Comment by tasn** [comment]
I think the combination of the latency between the US and Europe (what's your ping to etesync.com?) and the fact we do the sync synchronously don't help.
I have an idea how to solve it, assuming it's indeed the problem.

How did you install EteSync? Are you able to edit the source files and re-rerun etesync-dav if I tell you what to change? Would be easier to just quickly test the hypothesis with you (I will later implement it properly locally).

**Comment by Peter4487** [comment]
It's about 110ms to etesync.com

I've used the pre-built binary, but I'm happy to build and try it if it's helpful.

Is there a way I can make it show the current version? The web interface didn't seem to expose that.

**Comment by tasn** [comment]
Ping: not too bad. Though I guess this is enough to make it this slow. :|

Run `etesync-dav --version` from the command line. Though don't worry about it, I don't need it at the moment. I'll try to build a binary with a fix for you soon, though it most likely not be before next week unfortunately.
Are you able to run from source? That would save me having to build a binary for you and would mean we can test it sooner.

**Comment by Peter4487** [comment]
I see:
EteSync DAV version:  0.9.1
Radicale version:  2.1.11

Happy to run it from source if there are instructions you can point to. Otherwise, I'm in no rush :-)

**Comment by tasn** [comment]
I still haven't gotten to it unfortunately, but I have some good news that affect this ticket that I'll hopefully be able to share very soon! :)

**Comment by tasn** [comment]
Just for posterity: what I had in mind is just making the sync asynchronous. So it would first save it locally, and only then sync it with the EteSync server. Sort of a local caching layer. The problem with it, after taking a closer look, is that it makes error handling that much more complex. :|
We won't have a way to show errors to the user.

**Comment by tasn** [comment]
I completely understand. As I said though, you should expect some very good news soon that will solve this issue imminently!

**Comment by Peter4487** [comment]
Great--will i see the news on the blog?

**Comment by tasn** [comment]
Yeah, it would be there too! Unfortunately, the news won't mean an immediate solution, just more information... I can't wait to share, though it's not up to me. :)

**Comment by tasn** [comment]
A blog post will follow soon, but in the meanwhile there's an empty repo: https://github.com/etesync/EteSync-4-TbSync

We are building a native Thunderbird add-on. This should fix all of your issues.

**Comment by tasn** [comment]
It took some time, but here it is, I now have a fix for this problem. Are you able to test it by any chance? I just pushed the changes, so if you're able to test from source, that would be best. Otherwise, let me know, and I'll compile a binary for you.

I consider it fixed now, but please reopen if it doesn't fix it. Thanks, and looking forward to hearing from you.

**Comment by Peter4487** [comment]
Thanks! If there's instructions for compiling + patching I'm happy to do it myself. If not, I'll probably need you to build a binary for me.

**Comment by tasn** [comment]
Which OS for? Linux?

**Comment by tasn** [comment]
Hey,

Is it working for you? I plan on releasing a new version with this fix (and a few others) in the next few hours...

**Comment by tasn** [comment]
Released 0.12.0

**Comment by Peter4487** [comment]
Thanks very much for this, I'll try it now. And apologies for the delay, I've been swamped with work.

**Comment by tasn** [comment]
No worries, I know how it is. It took me a while too...

**Comment by Peter4487** [comment]
First impressions: sometimes things are fast, but there's another state where both linux-etesync-dav processes are _each_ taking up 100% of a CPU core. In that state things happen very slowly. I can guess when I'm in that state from the fan noise :-)

I'll have a more in-depth look soon.

**Comment by tasn** [comment]
Is that a new thing? Or was it also spinning hard while syncing before this change?
(you can compare side by side with an old binary)

**Comment by Peter4487** [comment]
It did that with the old binary too. I'm not sure about how often one vs. the other, nor am I sure about whether it's during syncing or not--but that would make sense.

**Comment by tasn** [comment]
It depends on your Thunderbird's sync settings, how often was it syncing before? So yeah, it would be more often now.

It being slow when it syncs: makes sense, as the syncing is a locking one, so while it's syncing it doesn't let anything else do anything. That's another thing I can fix, I guess. I can make it not use locks when there's only one user in the system and it's doing reads.

As for the CPU usage: that it's taking 100%. I have an idea for that too, but before I even go there, mind sharing your computer's specs? Also how many journals do you have? I'm asking because I'm not getting any of that here.

Thanks,
Tom

**Comment by Peter4487** [comment]
Hi Tom,

Thunderbird sync settings haven't changed. At present, I have six journals and they're set to sync every 30 minutes. I have an i7-6500u (4x2.5Ghz), 16GB RAM.

**Comment by tasn** [comment]
I released a new version earlier today that should make things even faster (and more consistently faster), as I fixed what I mentioned in my previous comment.

Thanks for your comment. Your specs are fine, and same with your number of journals.

Could you please try version 0.13.0 and see if it's still happening?

**Comment by Peter4487** [comment]
Hello tasn,

Thanks for the help and sorry for the delay. I've just installed 0.13.0 and it appears to have helped (no 100% CPU thing on startup, for instance). I'll keep monitoring, but thanks! This seems great.

Concerning syncing every 30 minutes: maybe I don't understand what that setting is doing? Is it checking everything on the calendar locally and on the server, comparing, and making any changes necessary? If so, I can understand why it doesn't need to happen every 30 minutes.

Will I still get new calendar changes via some other mechanism more often than every 30 minutes, such as some sort of push? Having my calendars (phone / computer) synchronize every 30 min only would be tolerable, but not ideal.

**Comment by tasn** [comment]
Glad to hear it seems better. Let me know if you notice any oddities.

You understand it correctly, and it's exactly what it does. My comment was just that in most cases people don't care about them syncing immediately like this (for example, I don't), but if you do, then please ignore my comment. I guess people have different use-cases.

The 30 minutes is for "pulling" changes, so for asking the server if anything is new. Pushing changes is done in addition and unrelated to this 30 minutes interval.

I hope this clarifies things.

**Comment by Peter4487** [comment]
Thanks very much for the information, that does clarify things.

I have noticed a couple instances where I'm seeing high CPU usage in two cores (~95%)

I'm also noticing events disappearing! It appears as though they are added to my calendar via Lightning / Thunderbird, but they aren't there later. Perhaps they're not being synced to the server, and when Thunderbird is restarted they're no longer there?

**Comment by tasn** [comment]
This is not normal. Could you run etesync-dav from the command line and see if you're witnessing any errors?

**Comment by Peter4487** [comment]
Hi again! Sorry for the long interval, life gets in the way. I really appreciate your continued work!

I'm seeing this error during periods of two processes at ~100% usage of a CPU core:
[alphanumerics] WARNING: Client provided invalid sync token 'http://radicale.org/ns/sync/[alphanumeric string]': Sync token are not supported (you can ignore this warning)

I see it seven times.

**Comment by tasn** [comment]
I could have reopened it. No worries though, we will discuss it in the other ticket. :)
