### ISSUE TITLE
[discussion] macOS Catalina dropping caldav support for tasks

### ISSUE THREAD

**Issue by zakkak** [etesync/etesync-dav#94]
Not sure whether this is the proper way to open a discusion on that issue, but I am not aware of any other communication medium for the project (apart from emailing @tasn ).

It appears that macOS Catalina and iOS 13 are shipping with a new reminders app which drops caldav support (and thus etesync support).

https://support.busymac.com/blog/112990

I think this needs to be made clear in the readme file and we should possibly look for good alternatives to suggest to macOS and iOS users.

**Comment by tasn** [comment]
Thanks for the update. For the lack of a better place for discussions, this is the right place.

God, this is annoying, though at least it's only for Reminders (I'll update the title), and not for calendars and contacts. Any good alternatives in mind?

**Comment by zakkak** [comment]
Not exactly a tasks/reminder alternative but one can use thunderbird with the TbSync addon to get access to tasks on macOS.

**Comment by tasn** [comment]
And there's the web app, which will further improve very soon! :)

**Comment by devurandom** [comment]
I just installed etesync-dav on macOS Catalina 10.15.3 and Reminders was able to show me the task list of the EteSync DAV account I set up in System Settings > Internet Accounts.

**Comment by tasn** [comment]
Thanks for the info @devurandom. Btw, the web app has improved a lot recently and there are more things coming: https://blog.etesync.com/web-client-task-management-overhaul/
