### ISSUE TITLE
Web UI not accessible through Docker on macOS

### ISSUE THREAD

**Issue by rsnitsch** [etesync/etesync-dav#98]
I'm trying to get etesync-dav running on macOS Mojave (10.14.6) using the Docker approach.

I can run the Docker commands successfully, and http://localhost:37358/ redirects to http://localhost:37359/. However, http://localhost:37359/ does not load in my browser.

I tried to add "-p 37359:37359" to the commandline parameters. Then, the behavior changes to "Connection was reset while loading".

In any case, the Docker instructions do not seem to work on macOS. Yes, I tried to disable my macOS firewall completely - it doesn't fix the issue.

I also tried to execute the commands:

```
docker run -it --rm -v etesync-dav:/data etesync/etesync-dav manage add USER_EMAIL
docker run -it --rm -v etesync-dav:/data etesync/etesync-dav certgen
```

... and then using https instead of http to connect to localhost:37358 and localhost:37359, but it didn't fix the problem. Instead, certgen reported the following error:

```
Generating a RSA private key
............................................................++++
.............................................................................................++++
unable to write 'random state'
writing new private key to '/data/etesync.key'
-----
Traceback (most recent call last):
  File "/usr/local/bin/etesync-dav", line 78, in <module>
    certgen(sys.argv[2:])
  File "/usr/local/bin/etesync-dav", line 69, in certgen
    macos_trust_cert()
  File "/usr/local/lib/python3.7/site-packages/etesync_dav/mac_helpers.py", line 39, in macos_trust_cert
    raise Error('this is not macOS.')
etesync_dav.mac_helpers.Error: this is not macOS.
```

By the way, it seems that it did save a certificate anyway, because the https connection did start working, but again, only for the 37358 port. The 37359 port is still not functional.

**Comment by tasn** [comment]
There are indeed multiple problems with Docker under macOS it seems. Thanks for reporting.
The first is that because it's not running in the main system, it can't properly do certgen. It's actually impossible to fix because it needs access to the host OS. Will need to think how to address this.
When it comes to the connection reset by peer: this is indeed a bug. It's because the web UI is only listening for connections from `localhost` so it's rejecting connections from the mac.

**Comment by tasn** [comment]
Fixed. It's not yet available in the docker image, but will be in the next one. As for fixing SSL: that's unrelated to this issue you reported, much more difficult, and requires people take the manual setup path anyway as we can't do it automatically.
