### ISSUE TITLE
Docs misleading: SSL cert not needed on macOS when using Thunderbird

### ISSUE THREAD

**Issue by rsnitsch** [etesync/etesync-dav#99]
After the Docker setup failed (see #98) I tried to run the prebuilt etesync-dav binary. I followed the instructions to generate/active the SSL certificate, because there was a huge warning box saying that on macOS this is necessary.

Then, however, in Thunderbird I was confronted with an SSL error. Thunderbird did not accept the self-signed SSL certificate.

Then, after trying all sorts of things, I tried it again WITHOUT enabling SSL, and it worked (facepalm!). Thus, I guess SSL is only needed if you add the CalDav/CardDav accounts in macOS directly (in the System Preferences at  "Internet Accounts").

You should clarify this in the docs and in the web UI warning.

I never intended to add the accounts to macOS directly. I only want to use it in Thunderbird. Therefore, I don't seem to need the SSL activation at all. It's rather the opposite. SSL breaks the Thunderbird integration.

**Comment by tasn** [comment]
Nice catch! Fixed.

Thanks!
